Repository openshift/lightspeed-service, pull requests merged in 2023-12, with the labels that each got.

#23 Implementing cache factory class
  app/constants.py
  app/endpoints/ols.py
  manifests/kustomization.yaml
  manifests/ols-redis.yaml
  requirements.txt
  src/cache/cache_factory.py
  src/cache/conversation_cache.py
  src/cache/in_memory_cache.py
  src/cache/redis_cache.py
  src/constants.py
Labels: approved, lgtm

#27 Specify gradio path at mount time, not instantiation time
  Makefile
  src/ui/gradio_ui.py
Labels: approved, lgtm

#29 Add unit tests for in memory cache
  .gitignore
  Makefile
  requirements-test.txt
  tests/integration/pytest.ini
  tests/integration/test_ols.py
  tests/unit/pytest.ini
  tests/unit/test_cache.py
Labels: approved, lgtm

#32 Making cache host/port configurable
  README.md
  src/cache/redis_cache.py
  src/constants.py
Labels: approved, lgtm

#35 Adding coverage transformer for PROW
  Makefile
  scripts/transform_coverage_report.py
Labels: approved, lgtm

#38 Set permissions so OLS image can run as arbitrary uids
  Containerfile
Labels: approved, lgtm

#31 Unit test skeleton for our internal modules
  src/query_helpers/yes_no_classifier.py
  tests/mock_classes/llm_chain.py
  tests/unit/query_helpers/test_yes_no_classifier.py
  utils/logger.py
Labels: approved, lgtm

#41 Refactor base OLS endpoint tests
  tests/integration/test_ols.py
  tests/mock_classes/langchain_interface.py
Labels: approved, lgtm

#42 Updated documentation to get the BAM Key
  README.md
  docs/bam_api_key.png
Labels: approved, ok-to-test, lgtm

#39 OLS-38: Complete work for OLS-38
  app/main.py
  src/ui/gradio_ui.py
  utils/config.py
  utils/logger.py
Labels: approved, tide/merge-method-squash, jira/valid-reference, lgtm

#43 More idiomatic comparison with None value
  app/endpoints/ols.py
  src/indexer/indexer.py
  src/ui/gradio_ui.py
Labels: approved, lgtm

#44 Removed unused imports
  app/main.py
  tests/integration/test_ols.py
  utils/json_tools.py
Labels: approved, lgtm

#47 Refactor cache and correct type hints
  src/cache/cache.py
  src/cache/cache_factory.py
  src/cache/in_memory_cache.py
  src/cache/redis_cache.py
  tests/unit/test_cache_factory.py
Labels: approved, lgtm

#37 chore: update deployment manifests
  manifests/ols-rbac.yaml
  manifests/ols.yaml
Labels: approved, ok-to-test, tide/merge-method-squash, lgtm

#46 Fixed typo (trivial)
  README.md
Labels: approved, lgtm

#45 Named lambda is the same as normal function
  src/indexer/indexer.py
Labels: approved, lgtm

#48 Testing of question validator
  src/query_helpers/question_validator.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, lgtm

#49 Unit tests for `parse_json_markdown` function
  tests/unit/utils/test_json_tools.py
Labels: approved, lgtm

#51 Fixed wrong message in Makefile when running integration tests
  Makefile
Labels: approved, lgtm

#52 Fixed multiple imports
  src/ui/gradio_ui.py
  utils/config.py
  utils/logger.py
Labels: approved, lgtm

#53 Fix + unit tests for parsing_and_checking_json
  tests/unit/utils/test_json_tools.py
  utils/json_tools.py
Labels: approved, lgtm

#54 Incorporate Ruff linter
  CONTRIBUTING.md
  Makefile
  pyproject.toml
Labels: approved, tide/merge-method-squash, lgtm

#55 More Ruff checks
  Makefile
  pyproject.toml
  src/query_helpers/task_performer.py
  src/query_helpers/task_processor.py
  tests/unit/test_cache_factory.py
  utils/logger.py
Labels: approved, lgtm

#56 introduce llm loader abstraction
  default.env
  requirements.txt
  src/llms/llm_loader.py
  src/llms/requirements.txt
  utils/logger.py
Labels: approved, tide/merge-method-squash, lgtm

#59 Catch JSON deserialization error for payload reading
  src/ui/gradio_ui.py
Labels: approved, lgtm

#58 Minor improvements in README.md
  README.md
Labels: approved, lgtm

#57 Use timeout for HTTP POST method to avoid infinite waits
  pyproject.toml
  src/ui/gradio_ui.py
Labels: approved, lgtm

#60 More idiomatic imports statements
  app/endpoints/ols.py
  src/cache/cache_factory.py
  src/cache/in_memory_cache.py
  src/cache/redis_cache.py
  src/docs/docs_summarizer.py
  src/indexer/indexer.py
  src/query_helpers/happy_response_generator.py
  src/query_helpers/question_validator.py
  src/query_helpers/task_performer.py
  src/query_helpers/task_processor.py
  src/query_helpers/task_rephraser.py
  src/query_helpers/yaml_generator.py
  src/query_helpers/yes_no_classifier.py
  tests/unit/test_cache_factory.py
Labels: approved, lgtm

#63 Fix: log file size must be number, not a string
  utils/logger.py
Labels: approved, lgtm

#64 Use proper HTTP protocol-related constants instead of magic constants
  src/ui/gradio_ui.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#65 Use sorted imports + enable more linters
  app/endpoints/feedback.py
  app/endpoints/ols.py
  app/main.py
  app/models/models.py
  scripts/transform_coverage_report.py
  src/cache/cache.py
  src/cache/cache_factory.py
  src/cache/in_memory_cache.py
  src/cache/redis_cache.py
  src/docs/docs_summarizer.py
  src/indexer/indexer.py
  src/llms/llm_loader.py
  src/query_helpers/happy_response_generator.py
  src/query_helpers/question_validator.py
  src/query_helpers/task_breakdown.py
  src/query_helpers/task_performer.py
  src/query_helpers/task_processor.py
  src/query_helpers/task_rephraser.py
  src/query_helpers/yaml_generator.py
  src/query_helpers/yes_no_classifier.py
  src/ui/gradio_ui.py
  tests/integration/test_ols.py
  tests/unit/test_cache.py
  tests/unit/test_cache_factory.py
  tests/unit/utils/test_json_tools.py
  utils/config.py
  utils/logger.py
  utils/model_context.py
Labels: approved, lgtm

#68 chore: add Helm chart
  README.md
  helm/.helmignore
  helm/Chart.yaml
  helm/templates/_helpers.tpl
  helm/templates/ols/clusterrole.yaml
  helm/templates/ols/clusterrolebinding.yaml
  helm/templates/ols/deployment.yaml
  helm/templates/ols/sa.yaml
  helm/templates/ols/secret.yaml
  helm/templates/ols/service.yaml
  helm/templates/redis/deployment.yaml
  helm/templates/redis/route-insight.yaml
  helm/templates/redis/service.yaml
  helm/values.yaml
Labels: approved, ok-to-test, lgtm

#61 Initial pass at abstracting the configuration into a central location and class.
  app/endpoints/feedback.py
  app/endpoints/ols.py
  app/main.py
  app/models/config.py
  default.env
  requirements.txt
  src/cache/cache_factory.py
  src/cache/in_memory_cache.py
  src/constants.py
  src/docs/docs_summarizer.py
  src/llms/llm_loader.py
  src/query_helpers/happy_response_generator.py
  src/query_helpers/question_validator.py
  src/query_helpers/task_breakdown.py
  src/query_helpers/task_performer.py
  src/query_helpers/task_processor.py
  src/query_helpers/task_rephraser.py
  src/query_helpers/yaml_generator.py
  src/query_helpers/yes_no_classifier.py
  tests/integration/test_ols.py
  tests/mock_classes/llm_loader.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
  tests/unit/test_cache.py
  tests/unit/test_cache_factory.py
  utils/config.py
  utils/model_context.py
Labels: approved, tide/merge-method-squash, lgtm
