Repository openshift/lightspeed-service, pull requests merged in 2023-11, with the labels that each got.

#1 Adding a Makefile to kickoff PROW pjrehearse
  Makefile
Labels: lgtm

#4 Improve yaml gen prompt to ensure only single yaml object response
  modules/task_processor.py
  modules/yaml_generator.py
Labels: approved, lgtm

#6 add an extremely primitive conversation caching implementation
  modules/conversation_cache.py
  modules/yaml_generator.py
  ols.py
Labels: approved, lgtm

#9 Add Logging class to start aggregating logging functionalities
  src/logger.py
Labels: approved, lgtm

#10 Add a minimal gradio interface with history
  gradio/main.py
  readme.md
  requirements.txt
Labels: approved, lgtm

#5 Implementing kube-rbac-proxy authentication/authorization
  Containerfile
  README.md
  config/kustomization.yaml
  config/namespace.yaml
  config/ols-client-test-rbac.yaml
  config/ols-client-test.yaml
  config/ols-rbac.yaml
  config/ols.yaml
Labels: approved, lgtm

#11 Updating Containerfile to use UBI-based Python 3.11
  Containerfile
  build-container.sh
Labels: approved, lgtm

#13 Restore port 8080 and refactor scripts directory structure, add images Make target
  Containerfile
  Makefile
  scripts/build-container.sh
Labels: approved, lgtm

#8 Adding contributing guide
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: approved, tide/merge-method-squash, lgtm

#12 embed the gradio ui within the fastapi server
  README.md
  modules/gradio_ui.py
  ols.py
Labels: approved, lgtm

#14 Add a Make run target, fix up port references to be consistent on 8080
  Makefile
  README.md
  modules/gradio_ui.py
  scripts/build-container.sh
Labels: approved, lgtm

#15 Fix Containerfile looking for legacy ./gradio folder
  Containerfile
Labels: approved, lgtm

#17 Include the user query in the conversation cache
  ols.py
Labels: approved, lgtm

#19 Mention the published lightspeed image on quay.io in readme
  README.md
Labels: approved, lgtm

#20 Add env vars for controlling image build behavior
  scripts/build-container.sh
Labels: approved, lgtm

#18 Adding class to handle configuration and first interconnection of logging class
  .gitignore
  default.env
  modules/gradio_ui.py
  ols.py
  src/config.py
  src/logger.py
Labels: approved, tide/merge-method-squash, lgtm

#26 Pytest skel
  Makefile
  modules/model_context.py
  ols.py
  pytest.ini
  requirements-test.txt
  requirements.txt
  test_ols.py
Labels: approved, tide/merge-method-squash, lgtm
