Repository openshift/lightspeed-service, pull requests merged in 2024-02, with the labels that each got.

#316 Log where we loaded the config file from
  ols/app/main.py
Labels: approved, lgtm

#318 OLS-89: Unit tests: missing credentials in config
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#319 OLS-89: New unit tests: equality operator
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#317 Separated integration tests coverage threshold
  CONTRIBUTING.md
  Makefile
Labels: approved, lgtm

#321 Increase unit test coverage threshold to 90%
  pyproject.toml
Labels: approved, lgtm

#320 OLS-89: Unit tests: checking dark corners of config loading
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#315 Instruct users to just run unit+integration test
  CONTRIBUTING.md
Labels: approved, lgtm

#324 OLS-89: Unit tests: Redis credentials configuration
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#325 More unit tests for Gradio UI
  tests/unit/ui/test_gradio_ui.py
Labels: approved, lgtm

#327 (doc) Info about Swagger UI
  README.md
Labels: approved, lgtm

#326 OLS-233: Use Optional type instead of | operator
  ols/app/models/config.py
  ols/app/models/models.py
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_docs.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/ui/gradio_ui.py
Labels: approved, jira/valid-reference, lgtm

#329 License in Swagger UI
  ols/app/main.py
Labels: approved, lgtm

#323 Added missing `make` command into contributing guide
  CONTRIBUTING.md
Labels: approved, lgtm

#322 OLS-261: Rename src/utils to rag
  ols/src/utils/__init__.py
  ols/src/utils/constants.py
  ols/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#332 Added missing types into `utils.config`
  ols/utils/config.py
Labels: approved, lgtm

#333 Added missing types into `cache.py` module
  ols/src/cache/cache.py
Labels: approved, lgtm

#334 Added missing types for return values
  ols/app/models/config.py
Labels: approved, lgtm

#335 Removed unused code
  ols/src/query_helpers/__init__.py
  tests/unit/query_helpers/test_query_helper.py
Labels: approved, lgtm

#281 OLS-256: Removed yaml category for Kubernetes queries
  ols/app/endpoints/ols.py
  ols/constants.py
  ols/src/query_helpers/question_validator.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#328 OLS-269: Always initialize index from test docs
  tests/integration/query_helpers/test_query_docs.py
Labels: approved, jira/valid-reference, lgtm

#336 Remove yaml generator
  ols/app/models/config.py
  ols/constants.py
  ols/src/query_helpers/yaml_generator.py
  tests/config/valid_config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/query_helpers/test_yaml_generator.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#331 OLS-157: Do request validation in pydantic model
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#50 Adding code coverage bits
  .codecov.yml
  Makefile
  scripts/codecov.sh
Labels: approved, lgtm

#337 Bug fix: word splitting
  Makefile
Labels: approved, lgtm

#330 OLS-116: Introducting Prometheus metrics
  README.md
  ols/app/endpoints/ols.py
  ols/app/main.py
  ols/app/metrics.py
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#225 OLS-212: Add test case for missing doc store scenario
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  tests/config/config_without_logging.yaml
  tests/config/singleprovider.e2e.template.config.yaml
  tests/config/test_app_endpoints.yaml
  tests/config/valid_config.yaml
  tests/config/valid_config_redis.yaml
  tests/integration/test_ols.py
  tests/mock_classes/langchain_interface.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#261 OLS-89: YAML configuration: redis conf from YAML, more validation
  ols/app/models/config.py
  ols/constants.py
  ols/src/cache/cache_factory.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/redis_cache.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/docs_summarizer.py
  tests/config/empty_secret.txt
  tests/config/redis_user.txt
  tests/config/redis_username.txt
  tests/config/valid_config_redis.yaml
  tests/config/with_openai_api_key.yaml
  tests/config/without_openai_api_key.yaml
  tests/unit/app/models/test_config.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/test_in_memory_cache.py
  tests/unit/test_redis_cache.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#341 Moved unit tests for caches to reflect source structure
  tests/unit/cache/test_cache_factory.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, lgtm

#343 Fix typo (trivial)
  CONTRIBUTING.md
Labels: approved, lgtm

#344 Use proper conversation ID in examples
  ols/app/models/models.py
Labels: approved, lgtm

#342 Use proper conversation ID in unit tests
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
  tests/unit/ui/test_gradio_ui.py
Labels: approved, lgtm

#340 Standard compound key separator
  ols/src/cache/cache.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, lgtm

#345 Minor contributing guide update
  CONTRIBUTING.md
Labels: approved, lgtm

#310 OLS-157: Ensure endpoints have in/out models
  ols/app/endpoints/feedback.py
  ols/app/endpoints/health.py
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_api.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_ols.py
  tests/unit/app/__init__.py
  tests/unit/app/endpoints/__init__.py
  tests/unit/app/endpoints/test_feedback.py
  tests/unit/app/endpoints/test_health.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/docs/test_doc_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#349 Test disabled question validator behaviour
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, lgtm

#242 OLS-158: Added e2e test case
  scripts/test-e2e-standalone.sh
  tests/config/singleprovider.e2e.template.config.yaml
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#339 OLS-89: LLM loader configuration cleanup
  ols/src/llms/llm_loader.py
  tests/config/empty_openai_api_key.yaml
  tests/integration/test_ols.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#350 Update: fix vulnerability in FastAPI
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#352 Fix broken e2e test
  pdm.lock
  tests/e2e/test_api.py
Labels: approved, lgtm

#353 Proper usage of `Optional` type
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/redis_cache.py
Labels: approved, lgtm

#354 Some missing config tests
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#356 Fix question validator return type
  ols/src/query_helpers/question_validator.py
Labels: approved, lgtm

#293 OLS-265: Implements an all-in-one container for testing
  Containerfile.rag
  README.md
Labels: approved, jira/valid-reference, lgtm

#358 Added missing `FastAPI` type
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#360 Fix comment: we don't use env.vars anymore
  ols/src/cache/cache_factory.py
Labels: approved, lgtm

#362 Remove obsolete tests
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#359 Proper `RetrievedNode` class declaration
  ols/utils/token_handler.py
Labels: approved, lgtm

#365 Separate routers
  ols/app/main.py
  ols/app/routers.py
Labels: approved, lgtm

#361 Change conversation to conversation_id
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yes_no_classifier.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
Labels: approved, lgtm

#363 OLS-233: Import all llm libs at once
  ols/src/llms/llm_loader.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#366 Missing kwargs types where needed
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/yes_no_classifier.py
Labels: approved, lgtm

#370 Few missing type declarations
  ols/app/models/models.py
  ols/app/routers.py
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#371 Removed leftover
  tests/integration/query_helpers/test_query_docs.py
Labels: approved, lgtm

#372 Trivial: reformat
  ols/src/query_helpers/query_docs.py
Labels: approved, lgtm

#374 E2E script needs to exit on errors
  scripts/test-e2e-standalone.sh
Labels: approved, lgtm

#369 OLS-295: Disable Gradio analytics
  ols/src/ui/gradio_ui.py
Labels: approved, jira/valid-reference, lgtm

#367 OLS-268: RAG: in OLS responses, support deep links into the OCP docs
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#377 Change script shebang from sh to bash
  scripts/test-e2e-standalone.sh
Labels: approved, lgtm

#378 Unit tests: init Redis code
  tests/mock_classes/redis.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, lgtm

#380 Refactor: LLMConfigurationError is not thrown from DocsSummarizer
  ols/app/endpoints/ols.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#381 History type for Gradio's Chat UI
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#382 (Trivial) typo
  ols/app/endpoints/ols.py
Labels: approved, lgtm

#384 Fix Markdown format in paragraph about keys storage solution
  README.md
Labels: approved, lgtm

#385 Link to OLS config example
  README.md
Labels: approved, lgtm

#386 OLS-31: Info about conversation cache configuration
  README.md
Labels: approved, jira/valid-reference, lgtm

#393 More realistic DocsSummarizer unit test
  tests/mock_classes/mock_query_engine.py
  tests/unit/docs/test_doc_summarizer.py
Labels: approved, lgtm

#391 Unit test: check for LLMConfiguration issue
  tests/unit/app/endpoints/test_ols.py
Labels: approved, lgtm

#389 Unit tests fix: use proper conversation ID
  tests/unit/docs/test_doc_summarizer.py
Labels: approved, lgtm

#390 New unit test: check for key existence
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#394 Use proper syntax highlighter (documentation, trivial)
  README.md
Labels: approved, lgtm

#395 Switch to langchain-openai dep instead of langchain-community
  ols/src/llms/llm_loader.py
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#387 OLS-293: Sequence diagram with basic flow
  README.md
  docs/sequence_diagram.png
  docs/sequence_diagram.uml
Labels: approved, jira/valid-reference, lgtm

#376 Replaces helm chart with an example set of YAML manifests.
  README.md
  examples/openshift-lightspeed.yaml
  helm/.helmignore
  helm/Chart.yaml
  helm/templates/_helpers.tpl
  helm/templates/ols/clusterrole.yaml
  helm/templates/ols/clusterrolebinding.yaml
  helm/templates/ols/deployment.yaml
  helm/templates/ols/sa.yaml
  helm/templates/ols/secret.yaml
  helm/templates/ols/service.yaml
  helm/templates/redis/deployment.yaml
  helm/templates/redis/route-insight.yaml
  helm/templates/redis/service.yaml
  helm/values.yaml
Labels: approved, lgtm

#402 OLS-254: Better check for conversation ID
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#401 OLS-254: Refactoring: retrieving conversation ID
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#404 OLS-254: Return response immediatelly to avoid type confusion
  ols/app/endpoints/ols.py
Labels: approved, jira/valid-reference, lgtm

#403 OLS-254: Proper type for `response` variable
  ols/app/endpoints/ols.py
Labels: approved, jira/valid-reference, lgtm

#397 Tolerate different response objects from different llm providers
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, lgtm

#405 OLS-254: Proper test for conversation ID from response
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#407 Fix exception message
  ols/src/cache/cache.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, lgtm

#383 OLS-264: Add config support for watsonx
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/constants.py
  ols/src/llms/llm_loader.py
  tests/config/config_without_logging.yaml
  tests/config/singleprovider.e2e.template.config.yaml
  tests/config/valid_config.yaml
  tests/config/valid_config_redis.yaml
  tests/unit/app/models/test_config.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#406 OLS-254: Refactor: store conversation history
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#409 OLS-254: Type issue has been fixed there - no need to have this warning
  ols/app/endpoints/ols.py
Labels: approved, jira/valid-reference, lgtm

#408 OLS-254: Refactoring: validate question function
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#400 OLS-305: Make LLMResponse include URLs for the embedding documents used to generate the response
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#411 OLS-254: Refactor: retrieve previous input
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#412 OLS-254: Refactor: call docs summarizer
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#418 Avoid nested patches, use multiple contexts
  tests/unit/query_helpers/test_query_docs.py
Labels: approved, lgtm

#413 OLS-254: Refactored: debug endpoint handler
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#416 OLS-58: Context window size configuration option
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#420 Add an e2e for rag content
  tests/e2e/test_api.py
Labels: approved, lgtm

#425 OLS-58: Truncating flag to be returned in response
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/integration/test_ols_debug.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/docs/test_doc_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#421 OLS-254: Reorder functions
  ols/app/endpoints/ols.py
Labels: approved, tide/merge-method-squash, jira/valid-reference, lgtm

#423 Avoid nested patching in tests
  tests/integration/test_ols.py
Labels: approved, lgtm

#410 OLS-332: avoid on-demand downloading of the embeddings model from HuggingFace
  .gitignore
  Containerfile
  Containerfile.rag
  Makefile
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/ui/gradio_ui.py
  scripts/download_embeddings_model.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#355 OLS-233: Make provider/model required inputs for LLMLoader
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
  tests/integration/test_ols.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/query_helpers/test_query_helper.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#427 OLS-114: REST API call counter
  ols/app/main.py
  ols/app/metrics.py
Labels: approved, jira/valid-reference, lgtm

#428 Refactor: getting embed model to be better testable
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, lgtm

#432 OLS-114: Use path in REST API call to counter metric
  ols/app/main.py
  ols/app/metrics.py
Labels: approved, jira/valid-reference, lgtm

#433 Bump the gradio timeout
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#435 OLS-113: REST API durations in metrics
  ols/app/main.py
  ols/app/metrics.py
Labels: approved, jira/valid-reference, lgtm

#430 OLS-114: Integration tests for metrics exposed by the service
  tests/integration/test_metrics.py
Labels: approved, jira/valid-reference, lgtm

#392 OLS-233: Nest dev_config llm_params
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/src/llms/llm_loader.py
  tests/config/singleprovider.e2e.template.config.yaml
  tests/e2e/test_api.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#434 Bump the ols e2e startup timeout
  scripts/test-e2e-standalone.sh
Labels: approved, lgtm

#442 Fixed checking if OLS has been started
  scripts/test-e2e-standalone.sh
Labels: approved, lgtm

#437 No need to explicitly return None value
  ols/app/endpoints/health.py
  tests/mock_classes/mock_retrievers.py
Labels: approved, lgtm

#439 Use explicit encoding when working with files
  ols/app/models/config.py
  ols/utils/config.py
  scripts/download_embeddings_model.py
  scripts/transform_coverage_report.py
Labels: approved, lgtm

#440 Simpler logic - not needed to nest conditions
  ols/app/models/config.py
Labels: approved, lgtm

#443 OLS-114: Check for all counters in metrics
  tests/integration/test_metrics.py
Labels: approved, jira/valid-reference, lgtm

#444 OLS-113: Check for histogram in metrics
  tests/integration/test_metrics.py
Labels: approved, jira/valid-reference, lgtm

#438 Member testing using sets
  ols/app/models/config.py
  ols/src/query_helpers/query_docs.py
Labels: approved, lgtm

#441 Use plain old teste function instead of methods where appropriate
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#445 OLS-311: Ability to start service from Python script
  Makefile
  README.md
  runner.py
Labels: approved, jira/valid-reference, lgtm

#447 Added missing types into `config.py`
  ols/app/models/config.py
Labels: approved, lgtm

#415 ols-241: - add TLS supported Example openshift manifest
  examples/openshift-lightspeed-tls.yaml
Labels: approved, jira/valid-reference, lgtm

#448 Added missing types into `main.py`
  ols/app/main.py
Labels: approved, lgtm

#449 Use port 8443 for tls so special permissions aren't needed
  examples/openshift-lightspeed-tls.yaml
Labels: approved, lgtm

#451 Fixed type for loglevel attribute
  ols/app/models/config.py
Labels: approved, lgtm

#452 Added missing type info in QuestionValidator
  ols/src/query_helpers/question_validator.py
Labels: approved, lgtm

#453 Proper return type (type hints)
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, lgtm

#454 Added missing unit tests in `config` module
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#455 Log traceback, not just error message
  ols/app/endpoints/ols.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_docs.py
Labels: approved, lgtm

#456 Refactor: QueryHelper class in it's own file
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  tests/integration/test_ols.py
  tests/unit/query_helpers/test_query_helper.py
Labels: approved, lgtm

#460 Minor: Test steps are regular functions
  tests/integration/test_ols.py
Labels: approved, lgtm

#463 (trivial) Added missing type hint
  ols/app/models/config.py
Labels: approved, lgtm

#458 Refactor: combine multiple patches into one with block
  tests/integration/test_ols.py
Labels: approved, lgtm

#465 Added missing conversation ID type hint
  ols/utils/query_filter.py
Labels: approved, lgtm

#467 Disable Gradio telemetry as soon as possible
  ols/src/ui/gradio_ui.py
  runner.py
Labels: approved, lgtm

#446 OLS-233: Llm loader modularity
  CONTRIBUTING.md
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/constants.py
  ols/src/llms/__init__.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/__init__.py
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/provider.py
  ols/src/llms/providers/registry.py
  ols/src/llms/providers/watsonx.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  tests/integration/test_ols.py
  tests/integration/test_ols_debug.py
  tests/mock_classes/llm_loader.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_openai.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/query_helpers/test_query_helper.py
Labels: approved, jira/valid-reference, lgtm

#466 Unit test for reduct_query function for no filters, one filter, and two filters
  tests/unit/app/endpoints/test_ols.py
Labels: approved, lgtm

#470 Change ecosystem for dependabot
  .github/dependabot.yml
Labels: approved, lgtm

#472 Update ruff settings
  pyproject.toml
Labels: approved, lgtm

#468 Query filter tests (for flow/branches not covered before)
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#476 OLS-241: Types for new auth code
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
  ols/utils/auth_dependency.py
Labels: approved, jira/valid-reference, lgtm

#474 Trivial change: TODO word is recognized by IDEs and some linters
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#477 Removed return statement for calls that returns nothing
  ols/app/models/config.py
Labels: approved, lgtm

#473 Refactor: simpler return statement, not need to use intermediate vari…
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/watsonx.py
Labels: approved, lgtm

#479 Param type hints
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/watsonx.py
Labels: approved, lgtm

#481 Fix: `module` is different type (`Module`) than module name (`Path`)
  ols/src/llms/__init__.py
Labels: approved, lgtm

#462 OLS-271: Load vector db once
  ols/app/endpoints/ols.py
  ols/app/main.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/rag_index/__init__.py
  ols/src/rag_index/index_loader.py
  ols/utils/config.py
  tests/integration/test_ols.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/rag_index/__init__.py
  tests/unit/rag_index/test_index_loader.py
Labels: approved, jira/valid-reference, lgtm

#480 OLS-272: Disable question validation for follow-up questions
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#457 Use IBM recommended params for granite model
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/watsonx.py
Labels: approved, lgtm

#486 Security update: bump-up Gradio
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#482 OLS-364: Updated and added missing type hints
  ols/app/models/config.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/provider.py
Labels: approved, jira/valid-reference, lgtm

#487 Move query filter after logger init
  ols/app/main.py
Labels: approved, lgtm

#490 Bump-up Prometheus client
  pdm.lock
Labels: approved, lgtm

#488 Add token limits to config
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/config/valid_config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#492 Added return type info
  ols/src/llms/providers/registry.py
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#491 Use latest Black [dev depencency]
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#495 Auth deps type hints
  ols/utils/auth_dependency.py
Labels: approved, lgtm
