Repository openshift/lightspeed-service, pull requests merged in 2024-04, with the labels that each got.

#678 Remove old rag containerfile
  Containerfile.rag
Labels: approved, lgtm

#679 Bump default context window size to 8000, to align w/ granite v2
  examples/olsconfig.yaml
  ols/constants.py
Labels: approved, lgtm

#681 OLS-117: combine provider+model enabled metric
  ols/app/metrics/__init__.py
  ols/app/metrics/metrics.py
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
  tests/integration/test_metrics.py
Labels: approved, jira/valid-reference, lgtm

#685 Update readme for local vector db
  README.md
Labels: approved, lgtm

#683 Fixed type hints in e2e tests
  tests/e2e/cluster_utils.py
Labels: approved, lgtm

#684 OLS-440: New config option: Postgres cache max-entries
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#687 OLS-420: Bump-up gradio and lanchchain direct dependencies
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#680 Bug fix: allow local e2e testing
  tests/e2e/test_api.py
Labels: approved, lgtm

#689 Fix deprecated import in bam
  ols/src/llms/providers/bam.py
Labels: approved, lgtm

#637 OLS-417: add support for authorization groups and fine-grained permissions
  examples/openshift-lightspeed-tls.yaml
  ols/app/endpoints/authorized.py
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
  ols/app/metrics/metrics.py
  ols/constants.py
  ols/utils/auth_dependency.py
  tests/config/cluster_install/ols_manifests.yaml
  tests/e2e/test_api.py
  tests/mock_classes/mock_k8s_api.py
  tests/scripts/utils.sh
  tests/unit/utils/test_auth_dependency.py
Labels: approved, jira/valid-reference, lgtm

#686 OLS-446: Token counter fix
  ols/app/metrics/token_counter.py
Labels: approved, jira/valid-reference, lgtm

#691 Optional metrics retriever return value
  tests/e2e/metrics_utils.py
Labels: approved, lgtm

#692 Check: default model and provider are required
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#655 Run metrics e2e tests in cluster envs
  tests/e2e/test_api.py
Labels: approved, lgtm

#682 chore: rename e2e util files
  tests/e2e/constants.py
  tests/e2e/helper_utils.py
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#676 OLS-375: Log OLS HTTP request+response payloads
  ols/app/main.py
Labels: approved, jira/valid-reference, lgtm

#696 Minor changes in integration tests
  tests/integration/__init__.py
  tests/integration/query_helpers/test_query_docs.py
  tests/integration/test_feedback.py
  tests/integration/test_openapi.py
  tests/integration/test_redis.py
Labels: approved, lgtm

#697 More precise test parameter description
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, lgtm

#698 Trivial: Logger.warn() call is deprecated
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#700 Move prompt templates to prompt file
  ols/constants.py
  ols/src/prompts/prompts.py
  ols/src/query_helpers/question_validator.py
Labels: approved, lgtm

#688 OLS-434: make target for response evaluation
  Makefile
  scripts/validate_response.py
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#677 OLS-439: Avoid multiple token calculation
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
  tests/unit/utils/test_auth_dependency.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#705 Refactor question validation logic
  ols/app/endpoints/ols.py
  ols/constants.py
  ols/src/prompts/prompts.py
  ols/src/query_helpers/question_validator.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, lgtm

#708 OLS-399: Use score to filter rag content
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#704 OLS-420: New WatsonxLLM used instead of deprecated one
  ols/src/llms/providers/watsonx.py
  pdm.lock
  pyproject.toml
  tests/mock_classes/mock_watsonxllm.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, jira/valid-reference, lgtm

#711 Llama-index is indeed used in production code
  pyproject.toml
Labels: approved, lgtm

#706 Info about other providers
  README.md
Labels: approved, lgtm

#709 OLS-117: Refactor provider/model metrics
  ols/app/main.py
  ols/app/metrics/__init__.py
  ols/app/metrics/metrics.py
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_ols_debug.py
  tests/integration/test_openapi.py
Labels: approved, jira/valid-reference, lgtm

#707 Documentation update: info about coverage
  CONTRIBUTING.md
Labels: approved, lgtm

#702 OLS-419: More detailed errors in HTTP REST API responses
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#713 e2e: Check for max default model+provider
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#712 remove unused constants
  ols/constants.py
  ols/src/prompts/prompts.py
Labels: approved, lgtm

#715 OLS-419 Conversation ID checks in REST API tests
  tests/e2e/test_api.py
Labels: approved, lgtm

#717 OLS-117: Disable built in metrics and prefix ols metrics with ols_
  ols/app/metrics/metrics.py
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
  tests/integration/test_metrics.py
Labels: approved, jira/valid-reference, lgtm

#673 OLS-139: Adds transcripts collection.
  ols/app/endpoints/ols.py
  tests/config/valid_config.yaml
  tests/e2e/cluster_utils.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#716 Minor e2e tests fixes
  tests/e2e/__init__.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#718 OLS-420: Updates for 2004 w15
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#719 Bug fix: schema generation
  scripts/generate_openapi_schema.py
Labels: approved, lgtm

#720 OSL-419: Added 401 and 403 HTTP codes for query REST API endpoint spec
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/models/models.py
Labels: approved, lgtm

#721 Consistent usage of parenthesis for all fixtures
  tests/e2e/test_api.py
  tests/unit/utils/test_auth_dependency.py
Labels: approved, lgtm

#723 Use regular `assert` statement consistently in all tests
  tests/unit/utils/test_query_filter.py
Labels: approved, lgtm

#730 OLS-373: map stories against TODOs
  ols/utils/token_handler.py
  scripts/validate_response.py
  tests/e2e/constants.py
Labels: jira/valid-reference, lgtm

#727 OLS-373: updated TODO with link to OLS-440
  ols/src/cache/cache_factory.py
  tests/unit/app/endpoints/test_ols.py
Labels: jira/valid-reference, lgtm

#728 OLS-373: Removed wrongly placed TODOs
  ols/src/prompts/prompt_generator.py
Labels: approved, jira/valid-reference, lgtm

#725 Proper names for fixtures not returning values
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_ols_debug.py
  tests/integration/test_openapi.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/utils/test_auth_dependency.py
Labels: approved, lgtm

#733 OLS-419: Better error messages for auth. endpoint
  docs/openapi.json
  ols/app/endpoints/authorized.py
  ols/utils/auth_dependency.py
Labels: jira/valid-reference

#734 OLS-373: Add TODO for OLS-495
  ols/app/endpoints/health.py
  ols/utils/auth_dependency.py
Labels: jira/valid-reference

#736 OLS-373: Add TODO for OLS-496
  ols/src/llms/providers/azure_openai.py
Labels: jira/valid-reference

#735 OLS-373: Add TODO for OLS-503
  ols/src/prompts/prompts.py
Labels: jira/valid-reference

#740 OLS-373: Don't lock types-requests version, not needed
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#741 OLS-373: Removed TODO: Redis won't be used soon
  ols/src/cache/redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#742 OLS-419: Metrics response is in plain text format
  docs/openapi.json
  ols/app/metrics/metrics.py
Labels: approved, jira/valid-reference, lgtm

#743 OLS-373: Link to Jira issue OLS-505
  scripts/questions_gen.py
Labels: approved, jira/valid-reference, lgtm

#745 OLS-373: Link to Jira issue OLS-506
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#744 OLS-419: Check content type in e2e tests
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#747 OLS-419: fixed feedback object example used on Swagger page
  docs/openapi.json
  ols/app/models/models.py
Labels: approved, jira/valid-reference, lgtm

#748 OLS-434: Use cluster url for evaluation
  scripts/validate_response.py
Labels: approved, jira/valid-reference, lgtm

#749 OLS-440: Read password for Postgres from file
  ols/app/models/config.py
  tests/config/postgres_password.txt
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#753 OLS-419: User feedback HTTP responses
  docs/openapi.json
  ols/app/endpoints/feedback.py
Labels: approved, jira/valid-reference, lgtm

#750 Fixed argument types
  scripts/validate_response.py
Labels: approved, lgtm

#754 Bump-up Ruff to version 0.3.7
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#752 OLS-419: Check conversation ID for feedback endpoint
  ols/app/models/models.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#756 Simplify `cluster_utils.py` a bit
  tests/e2e/cluster_utils.py
Labels: approved, lgtm

#757 OLS-419: Feedback e2e tests for improper input
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#758 Fix OLS-511: Bug when running `QueryFilter` unit tests alone
  tests/unit/utils/test_query_filter.py
Labels: approved, jira/valid-reference, lgtm

#738 move to newer azure api version
  ols/src/llms/providers/azure_openai.py
Labels: approved, lgtm

#759 Fix OLS-513: ability to run integration tests independently
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_ols_debug.py
  tests/integration/test_openapi.py
Labels: approved, jira/valid-reference, lgtm

#761 Fix run_suite exit code handling, avoid variable shadowing
  tests/scripts/test-e2e-cluster.sh
  tests/scripts/utils.sh
Labels: approved, lgtm

#760 Fixed argparser type
  tests/e2e/conftest.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#765 Integration test: query without improper conversation ID
  tests/integration/test_ols.py
Labels: approved, lgtm

#762 OLS-419: Removed inaccessible statement
  ols/app/endpoints/feedback.py
Labels: approved, jira/valid-reference, lgtm

#766 revert argparser type change for resp eval
  scripts/validate_response.py
Labels: approved, lgtm

#764 fix: only debug level logging includes access log
  runner.py
Labels: approved, lgtm

#763 OLS-469: Prompt limit check
  ols/app/endpoints/ols.py
  ols/src/query_helpers/question_validator.py
  ols/utils/token_handler.py
  tests/e2e/test_api.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#768 OLS-469: Prompt too long response in schema
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/models/models.py
Labels: approved, jira/valid-reference, lgtm

#767 Hint in contribution guide: detecting live and dead code
  CONTRIBUTING.md
Labels: approved, lgtm

#770 OLS-497: minimize image rebuilds by leveraging layer caching
  Containerfile
Labels: approved, jira/valid-reference, lgtm

#772 Use idiomatic dict call
  ols/app/models/config.py
Labels: approved, lgtm

#771 (Minor) added missing types for `__init__` methods
  ols/src/cache/postgres_cache.py
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#710 OLS-413: Make LLMResponse include page titles for referenced documents
  Containerfile
  Makefile
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/e2e/test_api.py
  tests/mock_classes/mock_query_engine.py
  tests/mock_classes/mock_retrievers.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#774 Improve feedback tests coverage
  tests/integration/test_feedback.py
  tests/unit/app/endpoints/test_feedback.py
Labels: approved, lgtm

#773 Elementary OpenAPI check in e2e tests
  tests/e2e/test_api.py
Labels: approved, lgtm

#634 OLS-440: Postgres-based cache
  ols/app/models/config.py
  ols/constants.py
  ols/src/cache/cache_error.py
  ols/src/cache/cache_factory.py
  ols/src/cache/postgres_cache.py
  pdm.lock
  pyproject.toml
  tests/config/valid_config_postgres.yaml
  tests/e2e/postgres_utils.py
  tests/e2e/test_api.py
  tests/unit/app/models/test_config.py
  tests/unit/cache/test_cache_factory.py
  tests/unit/cache/test_postgres_cache.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#777 Check HTTP status code first
  tests/e2e/test_api.py
Labels: approved, lgtm

#584 OLS-136: data to ingress
  .coveragerc
  .gitignore
  examples/openshift-lightspeed-tls.yaml
  ols/user_data_collection/__init__.py
  ols/user_data_collection/data_collector.py
  tests/config/cluster_install/ols_manifests.yaml
  tests/e2e/cluster_utils.py
  tests/e2e/test_api.py
  tests/unit/user_data_collection/test_data_collector.py
Labels: approved, jira/valid-reference, lgtm

#776 OLS-469: Model-specific default context window size
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#779 Ignore asserts in scripts the same way we ignored them in tests
  Makefile
Labels: approved, lgtm

#780 OLS-448: Update Fastapi and Pydantic
  pdm.lock
  pyproject.toml
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#782 Added more linters that are part of recent Ruff
  pyproject.toml
Labels: approved, lgtm

#784 Link to Jira issues #380 and #381
  ols/src/rag_index/index_loader.py
  ols/utils/config.py
  ols/utils/query_filter.py
  runner.py
Labels: approved, lgtm

#781 OLS-448: Bump project deps
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#778 OLS-136: Handle data collector errors
  ols/user_data_collection/data_collector.py
Labels: approved, jira/valid-reference, lgtm

#791 Integration tests stabilization
  tests/integration/test_ols.py
Labels: approved, lgtm

#724 OLS-375: added redaction of sensitive headers
  ols/app/main.py
  ols/constants.py
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#769 Use freeform prompt template for conversation
  ols/src/prompts/prompt_generator.py
  ols/src/prompts/prompts.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, lgtm

#790 Add sentiment field validation for feedback model
  docs/openapi.json
  ols/app/models/models.py
  tests/unit/app/models/test_models.py
Labels: approved, lgtm

#775 OLS-137: Feedback aggregator
  scripts/feedback_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#796 Update langchain dependencies
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#794 OLS-524: default parameter for history
  ols/src/query_helpers/docs_summarizer.py
  tests/unit/docs/test_doc_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#797 More unit and integration tests for sentiment attribute
  tests/integration/test_feedback.py
  tests/unit/app/models/test_models.py
Labels: approved, lgtm

#798 OLS-524: Don't use mutable default value in mock object
  tests/mock_classes/mock_summary.py
Labels: approved, jira/valid-reference, lgtm

#795 Collect logs from all containers in artifacts
  ols/user_data_collection/data_collector.py
  tests/config/cluster_install/ols_manifests.yaml
  tests/scripts/utils.sh
Labels: approved, lgtm

#800 More readable assert error message in e2e tests
  tests/e2e/test_api.py
Labels: approved, lgtm

#801 Removed Spacy lib
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#799 OLS-496: API version is parametrized for Azure OpenAI
  ols/src/llms/providers/azure_openai.py
  tests/config/valid_config_with_azure_openai.yaml
  tests/config/valid_config_with_azure_openai_api_version.yaml
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#803 Use consistent default values for truncation
  ols/constants.py
Labels: approved, lgtm

#793 Delete the /debug/query endpoint
  docs/openapi.json
  ols/app/endpoints/ols.py
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
  tests/integration/test_ols_debug.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, lgtm

#802 Context window size can be specified for provider + model
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#807 Info about PostgreSQL (documentation update)
  README.md
Labels: approved, lgtm

#805 Bump-up Torch(cpu) to 2.2.2
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#809 OLS-538: Exception chaining in query docs for better stack trace readiblity
  ols/src/query_helpers/query_docs.py
Labels: approved, jira/valid-reference, lgtm

#812 Test structure similar to code structure
  tests/unit/docs/__init__.py
  tests/unit/query_helpers/test_docs_summarizer.py
Labels: approved, lgtm

#814 Removed Redis from documentation in README.md
  README.md
Labels: approved, lgtm

#815 modify invalid query text for e2e test
  tests/e2e/test_api.py
Labels: approved, lgtm

#811 OLS-538: Better error message when token limit threshold is reached
  ols/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#813 OLS-495: Keep default user UUID and set it to "nil" UUID
  ols/constants.py
  ols/utils/auth_dependency.py
Labels: approved, jira/valid-reference, lgtm

#804 Remove the "no rag used in response" prefix message from ols responses
  ols/app/endpoints/ols.py
  ols/constants.py
  ols/src/prompts/prompt_generator.py
  ols/src/query_helpers/docs_summarizer.py
  scripts/validate_response.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, lgtm

#816 Retrieve clusterversion object by correct name
  ols/user_data_collection/data_collector.py
Labels: approved, lgtm

#817 OLS-527: Bump-up libs, 2024 week 17
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#818 Remove obsolete todo
  runner.py
Labels: approved, lgtm

#808 Add buffer to token count
  ols/constants.py
  ols/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#789 OLS-508: Ability to control collector via file existence
  ols/user_data_collection/data_collector.py
  tests/e2e/cluster_utils.py
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#822 OLS-549: Strip whitespaces from response
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#821 OLS-549: Proper output to CSV file
  scripts/feedback_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#828 OLS-527: bump up libs
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#820 consider role for history tokens
  ols/app/endpoints/ols.py
  ols/src/prompts/prompt_generator.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/prompts/test_prompt_generator.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#829 OLS-538: Unit test for too long prompt exception
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#827 OLS-506: Remove redundant standalone tests
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#810 OLS-538: Check final token count before reaching LLM
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#830 OLS-529: Bump-up llama_index to latest version
  ols/src/query_helpers/docs_summarizer.py
  ols/src/rag_index/index_loader.py
  ols/utils/token_handler.py
  pdm.lock
  pyproject.toml
  scripts/questions_gen.py
  tests/unit/rag_index/test_index_loader.py
Labels: approved, jira/valid-reference, lgtm

#833 OLS-538: Refactor get_token_handler method
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
  ols/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#834 OLS-447: Unit test for checking provider type
  tests/unit/llms/providers/test_providers.py
Labels: approved, tide/merge-method-squash, jira/valid-reference, lgtm

#831 Fix issue OLS-553: process files with wrong paths gracefully
  scripts/feedback_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#835 Coverage report run in virtual environment via PDM
  pyproject.toml
Labels: approved, lgtm

#836 OLS-447: Unit tests: handling known and unknown parameters by BAM and Watsonx providers
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, jira/valid-reference, lgtm

#837 Update RAG content: OLS-517, OLS-530, page exclusion, OCP docs update
  Containerfile
  Makefile
Labels: approved, lgtm

#838 Ability to aggregate full conversation history for user feedback
  scripts/feedback_aggregator.py
Labels: approved, lgtm

#841 Consistent naming for mock objects
  tests/integration/test_ols.py
  tests/mock_classes/mock_langchain_interface.py
  tests/mock_classes/mock_llm_chain.py
  tests/mock_classes/mock_llm_loader.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, lgtm

#825 OLS-506: Move testing script ot tests
  Makefile
  tests/e2e/test_api.py
  tests/scripts/validate_response.py
Labels: approved, jira/valid-reference, lgtm

#843 OLS-137: Ability to export referenced documents in conversation history
  scripts/feedback_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#842 OLS-447: Unit test: default params to None
  tests/unit/llms/providers/test_openai.py
Labels: approved, jira/valid-reference, lgtm

#840 Added all commands that required PDM-managed virtual environment
  pyproject.toml
Labels: approved, lgtm

#848 Proper type for request headers
  ols/user_data_collection/data_collector.py
Labels: approved, lgtm

#849 Proper Watsonx name
  ols/app/models/config.py
  ols/src/llms/providers/watsonx.py
  tests/unit/app/models/test_config.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, lgtm
