Repository openshift/lightspeed-service, pull requests merged in 2024-01, with the labels that each got.

#69 Verify project sources with Python 3.11 expected idioms
  pyproject.toml
Labels: approved, lgtm

#73 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#75 Fully typed in-memory cache
  src/cache/in_memory_cache.py
Labels: approved, lgtm

#71 Prevent globbing in shellscript
  scripts/build-container.sh
Labels: approved, lgtm

#72 Update contrib install instructions
  CONTRIBUTING.md
  requirements-test.txt
Labels: approved, ok-to-test, lgtm

#79 `mock_classes` is a package, so it should contains `__init__.py`
  tests/mock_classes/__init__.py
Labels: approved, lgtm

#78 Imports statements are sorted + added new linter rule
  app/endpoints/ols.py
  app/main.py
  app/models/config.py
  pyproject.toml
  src/cache/cache_factory.py
  src/docs/docs_summarizer.py
  src/llms/llm_loader.py
  src/query_helpers/happy_response_generator.py
  src/query_helpers/question_validator.py
  src/query_helpers/yaml_generator.py
  src/query_helpers/yes_no_classifier.py
  tests/integration/test_ols.py
  tests/unit/test_cache_factory.py
  utils/config.py
Labels: approved, lgtm

#80 Type info for functions without return value
  app/models/config.py
  src/cache/redis_cache.py
  src/query_helpers/happy_response_generator.py
  src/query_helpers/question_validator.py
  src/query_helpers/yaml_generator.py
  src/query_helpers/yes_no_classifier.py
  tests/integration/test_ols.py
  utils/config.py
  utils/logger.py
Labels: approved, lgtm

#70 Help in Makefile shown using `make help` phony target
  Makefile
Labels: approved, lgtm

#76 Prevent double call of `file.close()`
  scripts/transform_coverage_report.py
Labels: approved, lgtm

#77 Use explicit verbose kwarg in question validator
  src/query_helpers/question_validator.py
Labels: approved, ok-to-test, lgtm

#83 Ignore cache directories - these should not be pushed into the repo
  .gitignore
Labels: approved, lgtm

#81 Added more types for functions called from unit tests
  src/cache/in_memory_cache.py
  src/query_helpers/question_validator.py
  src/query_helpers/yes_no_classifier.py
Labels: approved, lgtm

#82 Ability to export coverage report into interactive HTML
  .gitignore
  Makefile
Labels: approved, lgtm

#87 Integer values should be really converted into integer
  app/models/config.py
  utils/config.py
Labels: approved, lgtm

#85 Enable Flake8-like type checking
  pyproject.toml
Labels: approved, lgtm

#86 Fixed type related errors
  app/endpoints/ols.py
  src/indexer/indexer.py
  src/llms/llm_loader.py
Labels: approved, lgtm

#89 Proper endpoints in integration tests + 2 negative test cases
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#91 Use the constant that used to be defined for this purpose
  utils/config.py
Labels: approved, lgtm

#95 Better HTTP status codes
  app/endpoints/ols.py
Labels: approved, lgtm

#92 Code coverage checks + updated contributing documentation a bit
  CONTRIBUTING.md
  pyproject.toml
Labels: approved, lgtm

#84 Fixed docstyle in sources
  app/endpoints/feedback.py
  app/endpoints/ols.py
  app/main.py
  app/models/models.py
  app/utils.py
  scripts/transform_coverage_report.py
  src/cache/cache_factory.py
  src/cache/in_memory_cache.py
  src/cache/redis_cache.py
  src/docs/docs_summarizer.py
  src/llms/llm_loader.py
  src/query_helpers/happy_response_generator.py
  src/query_helpers/question_validator.py
  src/query_helpers/yaml_generator.py
  src/query_helpers/yes_no_classifier.py
  tests/mock_classes/langchain_interface.py
  tests/mock_classes/llm_chain.py
  utils/json_tools.py
  utils/logger.py
Labels: approved, lgtm

#98 Really check line length on CI
  pyproject.toml
  src/constants.py
Labels: approved, lgtm

#94 Two new integration tests for query post endpoint
  tests/integration/test_ols.py
Labels: approved, lgtm

#99 Get rid of unused JSON tools
  tests/unit/utils/test_json_tools.py
  utils/json_tools.py
Labels: approved, lgtm

#97 Setup Google doc style convention for Ruff (and thus for CI)
  pyproject.toml
Labels: approved, lgtm

#88 Updated PR template: checkbox about linters
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#103 Refactoring: unknown question type handling
  app/endpoints/ols.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#93 Pre-commit hook settings
  CONTRIBUTING.md
  hooks/pre-commit
Labels: approved, tide/merge-method-squash, lgtm

#104 100% unit test coverage for logging module
  tests/unit/utils/test_logger.py
Labels: approved, lgtm

#100 Added proper docstrings (that can be linted) into all existing unit tests
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
  tests/unit/test_cache.py
  tests/unit/test_cache_factory.py
Labels: approved, lgtm

#105 Idiomatic checks in model config checking
  app/models/config.py
Labels: approved, lgtm

#101 Docstrings in all integration tests
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#102 Docstrings in all mocks classes
  tests/mock_classes/__init__.py
  tests/mock_classes/langchain_interface.py
  tests/mock_classes/llm_chain.py
  tests/mock_classes/llm_loader.py
Labels: approved, lgtm

#106 Merge project structure
  Containerfile
  Makefile
  ols/__init__.py
  ols/app/__init__.py
  ols/app/constants.py
  ols/app/endpoints/__init__.py
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
  ols/app/main.py
  ols/app/models/__init__.py
  ols/app/models/config.py
  ols/app/models/models.py
  ols/app/utils.py
  ols/src/__init__.py
  ols/src/cache/__init__.py
  ols/src/cache/cache.py
  ols/src/cache/cache_factory.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/redis_cache.py
  ols/src/constants.py
  ols/src/docs/__init__.py
  ols/src/docs/docs_summarizer.py
  ols/src/indexer/indexer.py
  ols/src/llms/__init__.py
  ols/src/llms/llm_loader.py
  ols/src/llms/requirements.txt
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/happy_response_generator.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  ols/src/ui/__init__.py
  ols/src/ui/gradio_ui.py
  ols/utils/__init__.py
  ols/utils/config.py
  ols/utils/logger.py
  pyproject.toml
  requirements.txt
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
  tests/unit/test_cache.py
  tests/unit/test_cache_factory.py
  tests/unit/utils/test_logger.py
Labels: approved, lgtm

#107 Use Path module
  tests/unit/utils/test_logger.py
Labels: approved, lgtm

#108 Trivial refactoring: use `return` directly
  tests/unit/test_cache_factory.py
Labels: approved, lgtm

#109 Don't need to use aliases during import
  ols/app/models/config.py
  ols/src/indexer/indexer.py
  ols/src/llms/llm_loader.py
  ols/utils/config.py
Labels: approved, lgtm

#110 Don't need to call `str` inside f-strings
  ols/src/docs/docs_summarizer.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/happy_response_generator.py
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#111 Docstrings update, round #1
  ols/app/main.py
  ols/src/cache/__init__.py
  ols/src/cache/cache.py
  ols/src/cache/cache_factory.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/redis_cache.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/happy_response_generator.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  ols/src/ui/__init__.py
  ols/src/ui/gradio_ui.py
  ols/utils/__init__.py
  ols/utils/config.py
  ols/utils/logger.py
  scripts/transform_coverage_report.py
Labels: approved, lgtm

#113 Update contributing with docstring style section
  CONTRIBUTING.md
Labels: approved, lgtm

#117 (Minor refactor) directly return value
  ols/src/cache/in_memory_cache.py
Labels: approved, lgtm

#120 Info about code coverage report
  CONTRIBUTING.md
Labels: approved, lgtm

#112 Fix run command in readme
  README.md
Labels: approved, lgtm

#116 Use custom exception
  ols/app/models/config.py
Labels: approved, lgtm

#115 Public packages should be documented via docstrings
  ols/__init__.py
  ols/app/__init__.py
  ols/app/endpoints/__init__.py
  ols/app/models/__init__.py
  ols/src/__init__.py
  ols/src/docs/__init__.py
  ols/src/llms/__init__.py
  ols/src/llms/llm_loader.py
Labels: approved, lgtm

#124 move description section to top of PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#118 Unit tests for YAML generator class
  tests/unit/query_helpers/test_yaml_generator.py
Labels: approved, tide/merge-method-squash, lgtm

#134 docs: fix curl example in readme
  README.md
Labels: approved, lgtm

#127 OLS-186: Renamed: these tests checks InMemoryCache class only
  tests/unit/test_in_memory_cache.py
Labels: approved, jira/valid-reference, lgtm

#122 OLS-186: Use `@patch` instead of monkeypatch
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#125 OLS-186: No `pass` for abstract methods
  ols/src/cache/cache.py
Labels: approved, jira/valid-reference, lgtm

#129 OLS-155: Add explicit env for logging level when logging to file
  default.env
  ols/utils/logger.py
  tests/unit/utils/test_logger.py
Labels: approved, jira/valid-reference, lgtm

#126 OLS-186: Cache factory returning Redis interface: unit test
  tests/unit/test_cache_factory.py
Labels: approved, jira/valid-reference, lgtm

#140 OLS-83: Fixed logic in invalid state checks
  ols/app/endpoints/ols.py
Labels: approved, jira/valid-reference, lgtm

#145 Set owners file to clean slate
  OWNERS
Labels: approved, lgtm

#137 OLS-83: Docstyle checks on CI
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#138 Fixed wrong return type
  ols/app/endpoints/ols.py
Labels: approved, lgtm

#133 OLS-186: Docs summarizer unit tests
  tests/mock_classes/mock_llama_index.py
  tests/mock_classes/mock_query_engine.py
  tests/mock_classes/mock_summary.py
  tests/unit/docs/test_doc_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#139 OLS-83: Specify optional types where it is needed
  ols/src/query_helpers/yaml_generator.py
  ols/utils/logger.py
Labels: approved, jira/valid-reference, lgtm

#143 Check if provider is supported
  ols/src/llms/llm_loader.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#152 OLS-155: Remove ability for logging to file
  default.env
  ols/app/models/config.py
  ols/utils/config.py
  ols/utils/logger.py
  tests/unit/utils/test_logger.py
Labels: approved, jira/valid-reference, lgtm

#160 OLS-83: Info how to patch (docstring)
  tests/mock_classes/llm_chain.py
  tests/mock_classes/mock_llama_index.py
  tests/mock_classes/redis.py
Labels: approved, jira/valid-reference, lgtm

#148 OLS-155: Merge constants under single project level module
  ols/app/constants.py
  ols/app/endpoints/ols.py
  ols/app/models/config.py
  ols/constants.py
  ols/src/cache/cache_factory.py
  ols/src/cache/redis_cache.py
  ols/src/docs/docs_summarizer.py
  ols/src/indexer/indexer.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  ols/utils/config.py
  tests/integration/test_ols.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/test_cache_factory.py
Labels: approved, jira/valid-reference, lgtm

#151 OLS-160: Definition of Done
  CONTRIBUTING.md
Labels: approved, jira/valid-reference, lgtm

#156 OLS-83: Added missing type hints into DocsSummarizer
  ols/src/docs/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#157 OLS-83: Loglevel as name everywhere
  ols/utils/config.py
Labels: approved, jira/valid-reference, lgtm

#158 OLS-83: Use imperative mood in mock classes: according PEP 257
  tests/mock_classes/langchain_interface.py
  tests/mock_classes/llm_chain.py
  tests/mock_classes/llm_loader.py
  tests/mock_classes/mock_llama_index.py
  tests/mock_classes/mock_query_engine.py
  tests/mock_classes/mock_summary.py
  tests/mock_classes/redis.py
Labels: approved, jira/valid-reference, lgtm

#159 OLS-83: Use imperative mood in sources
  ols/src/cache/cache_factory.py
  ols/src/cache/in_memory_cache.py
  ols/src/indexer/indexer.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  ols/src/ui/gradio_ui.py
  ols/utils/logger.py
Labels: approved, jira/valid-reference, lgtm

#155 clean env vars before logging unit test
  tests/unit/utils/test_logger.py
Labels: approved, lgtm

#147 OLS-83: Improved improper LLM model configuration checks
  ols/src/llms/llm_loader.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#162 OLS-211: Removed LLMLoader param override for OpenAI
  ols/src/llms/llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#169 OLS-83: Enable D401 check on CI
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#170 Remove commented code in test
  tests/unit/test_cache_factory.py
Labels: approved, lgtm

#172 OLS-83: Use @patch in unit tests for yes-no classifier
  tests/unit/query_helpers/test_yes_no_classifier.py
Labels: approved, jira/valid-reference, lgtm

#164 Use LLMChain for base prompt llm invocation
  ols/app/endpoints/ols.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#173 OLS-83: Use `@patch` it test-yaml-generator
  tests/unit/query_helpers/test_yaml_generator.py
Labels: approved, jira/valid-reference, lgtm

#177 Raise exception when selected LLM can not be loaded
  ols/src/llms/llm_loader.py
  tests/integration/test_ols.py
Labels: approved, lgtm

#171 Tips and hints for writing unit tests
  CONTRIBUTING.md
Labels: approved, lgtm

#154 OLS-155: Set project line length
  ols/app/models/models.py
  ols/constants.py
  ols/src/docs/docs_summarizer.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  ols/utils/config.py
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#149 OLS-155: Use constants in prompt template
  ols/constants.py
Labels: approved, jira/valid-reference, lgtm

#168 Fix enabling dev ui via env
  default.env
  ols/app/main.py
  ols/app/models/config.py
  ols/utils/config.py
Labels: approved, lgtm

#175 OLS-186: Checks how improper LLM loading is handled by LLM loader
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#178 Use match-case instead of if-elseif flow
  ols/src/cache/cache_factory.py
Labels: approved, lgtm

#180 OLS-186: Slightly better unit tests for logger
  tests/unit/utils/test_logger.py
Labels: approved, jira/valid-reference, lgtm

#179 Info about capturing in unit tests and integration tests
  CONTRIBUTING.md
Labels: approved, lgtm

#186 Get rid of `monkeypatch` from integration tests
  tests/integration/test_ols.py
Labels: approved, lgtm

#183 OLS-151: Info about tests
  CONTRIBUTING.md
Labels: approved, jira/valid-reference, lgtm

#182 OLS-186: Final LLM loader unit tests
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#187 OLS-153: Fix local var type
  ols/src/docs/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#189 OLS-102: Version OLS API endpoints
  README.md
  ols/app/endpoints/feedback.py
  ols/app/endpoints/health.py
  ols/app/endpoints/ols.py
  ols/app/main.py
  ols/app/models/models.py
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#190 Fix InvalidConfigurationError docstring format
  ols/app/models/config.py
Labels: approved, lgtm

#191 Fix unit test: no key to be passed everywhere
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#193 OLS-84: Refactoring: require LLM init to return the right object or fail in all cases
  ols/src/llms/llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#188 OLS-153: Ability to perform type checks from CLI
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  requirements-test.txt
Labels: approved, jira/valid-reference, lgtm

#194 OLS-153: Added missing type info for all LLM constructors
  ols/src/llms/llm_loader.py
Labels: approved, tide/merge-method-squash, jira/valid-reference, lgtm

#195 Typed params (minor)
  ols/src/llms/llm_loader.py
Labels: approved, lgtm

#196 Updated Mypy settings - for new version
  pyproject.toml
Labels: approved, lgtm

#197 Fix URL for our UI
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#201 Docupdate: Info about exception that can be thrown
  ols/src/cache/redis_cache.py
Labels: approved, lgtm

#202 Doc update: An example how 'raises:' should be written in docstrings
  CONTRIBUTING.md
Labels: approved, lgtm

#198 Bug fix: initializing BAM LLM in new version
  ols/src/llms/llm_loader.py
  requirements.txt
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#174 OLS-185: improve unit test coverage of ols.app module.
  ols/app/models/config.py
  ols/constants.py
  tests/unit/test_app_endpoints.py
  tests/unit/test_models.py
  tests/unit/utils/test_app_utils.py
Labels: approved, jira/valid-reference, lgtm

#203 Fix type errors so we can enable type checking
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  requirements-test.txt
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/test_app_endpoints.py
Labels: approved, lgtm

#204 Minor contributing guide improvement
  CONTRIBUTING.md
Labels: approved, lgtm

#199 Remove unused url parameter in LLMLoader
  ols/src/llms/llm_loader.py
Labels: approved, lgtm

#206 Don't expect all types libs
  pyproject.toml
Labels: approved, lgtm

#205 OLS-153: Updated pre-commit hook + updated contributing guide accordingly
  CONTRIBUTING.md
  hooks/pre-commit
Labels: approved, jira/valid-reference, lgtm

#209 (Trivial) Use lowercase local vars
  tests/unit/ui/test_gradio_ui.py
Labels: approved, lgtm

#184 OLS-40: Llm loader parent error
  ols/src/llms/llm_loader.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#208 added config for weekly dependency checks for dependabot
  .github/dependabot.yml
Labels: approved, needs-ok-to-test, lgtm

#200 OLS-233: Llmloader unify error handling
  ols/src/llms/llm_loader.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#210 Use lowercase local vars in LLM loader tests
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#165 Ols 212: Missing documentation about index store
  README.md
  ols/src/docs/docs_summarizer.py
Labels: approved, ok-to-test, lgtm

#211 Proper case for identifiers in all sources
  ols/app/main.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/redis_cache.py
  ols/src/ui/gradio_ui.py
  tests/unit/ui/test_gradio_ui.py
Labels: approved, lgtm

#213 Add comment about model_config attr
  ols/app/models/models.py
Labels: approved, lgtm

#214 Enable more linters for `make verify` and for CI
  pyproject.toml
Labels: approved, lgtm

#220 Unit tests need to be updated after LLM loader was refactored
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#221 Unit tests improvements: exception checks should not be too broad
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
  tests/unit/test_cache_factory.py
Labels: approved, lgtm

#166 OLS-89: Update OLS to consume config yaml
  README.md
  bam_api_key.txt
  default.env
  ols/app/main.py
  ols/app/models/config.py
  ols/constants.py
  ols/utils/config.py
  olsconfig.yaml
  openai_api_key.txt
  tests/config/redis_password.txt
  tests/config/redis_user.txt
  tests/config/secret.txt
  tests/config/test_app_endpoints.txt
  tests/config/test_app_endpoints.yaml
  tests/config/valid_config.yaml
  tests/config/valid_config_redis.yaml
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yaml_generator.py
  tests/unit/test_app_endpoints.py
  tests/unit/test_config.py
  tests/unit/test_models.py
Labels: approved, jira/valid-reference, lgtm

#226 Get rid of `in-memory` option
  ols/src/cache/cache_factory.py
Labels: approved, lgtm

#223 OLS-103 - Completed basic retriever
  .gitignore
  ols/src/query_helpers/query_docs.py
  requirements.txt
  tests/integration/query_helpers/test_query_docs.py
  tests/mock_classes/mock_retrievers.py
  tests/unit/query_helpers/test_query_docs.py
Labels: approved, lgtm

#217 Add QueryHelper parent
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  tests/unit/query_helpers/test_query_helper.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/query_helpers/test_yaml_generator.py
  tests/unit/query_helpers/test_yes_no_classifier.py
Labels: approved, lgtm

#233 Fix enable UI configuration option
  README.md
  ols/app/main.py
  ols/app/models/config.py
  tests/unit/test_models.py
Labels: approved, lgtm

#232 Enable linting for config.py
  ols/utils/config.py
Labels: approved, lgtm

#234 Use more idiomatic `pytest.fail()` instead of `assert False`
  tests/unit/test_config.py
Labels: approved, lgtm

#236 Use `type` in Python 3.9 or above
  tests/unit/test_config.py
Labels: approved, lgtm

#231 Raise exception when config file is missing
  ols/utils/config.py
  tests/unit/test_config.py
Labels: approved, lgtm

#227 OLS-89: Config yaml follow-ups
  .gitignore
  README.md
  bam_api_key.txt
  openai_api_key.txt
  tests/config/test_app_endpoints.txt
  tests/config/test_app_endpoints.yaml
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference

#237 More specific error message
  ols/src/query_helpers/yes_no_classifier.py
Labels: approved, lgtm

#218 pin package types-requests<2.31.0.7
  requirements-test.txt
Labels: approved, lgtm

#215 feat: [OLS-104] Add token handler utility for context
  ols/src/utils/__init__.py
  ols/src/utils/constants.py
  ols/src/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#230 Docs summarizer to query helpers
  ols/app/endpoints/ols.py
  ols/src/docs/__init__.py
  ols/src/query_helpers/docs_summarizer.py
  tests/mock_classes/mock_llama_index.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/test_app_endpoints.py
Labels: approved, lgtm

#228 Define e2e execution logic in ols repo
  Makefile
  scripts/test-e2e-standalone.sh
  tests/config/singleprovider.e2e.template.config.yaml
Labels: approved, lgtm

#239 Fix: `VectorDB` parameter is not optional
  ols/src/query_helpers/query_docs.py
Labels: approved, lgtm

#240 Refactoring: don't use method name from superclass
  ols/app/models/config.py
  ols/utils/config.py
  tests/unit/test_models.py
Labels: approved, lgtm

#246 Make Black happy again
  ols/app/models/models.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/query_docs.py
  ols/src/utils/token_handler.py
  tests/integration/query_helpers/test_query_docs.py
  tests/mock_classes/mock_retrievers.py
  tests/unit/query_helpers/test_query_docs.py
  tests/unit/test_models.py
  tests/unit/utils/test_app_utils.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#244 (Minor) Fixed typo in exception message
  ols/src/query_helpers/query_docs.py
  tests/unit/query_helpers/test_query_docs.py
Labels: approved, lgtm

#245 Specific exception message in question validator
  ols/src/query_helpers/question_validator.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, lgtm

#247 Removed unecessarry statement
  tests/mock_classes/mock_retrievers.py
  tests/mock_classes/redis.py
Labels: approved, lgtm

#131 OLS-204: logging refactoring
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
  ols/app/main.py
  ols/app/models/config.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/__init__.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_docs.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
  ols/src/ui/gradio_ui.py
  ols/src/utils/token_handler.py
  ols/utils/config.py
  ols/utils/logger.py
  ols/utils/logging.py
  olsconfig.yaml
  tests/config/test_app_endpoints.yaml
  tests/config/valid_config.yaml
  tests/config/valid_config_redis.yaml
  tests/unit/test_config.py
  tests/unit/test_models.py
  tests/unit/ui/test_gradio_ui.py
  tests/unit/utils/test_logger.py
Labels: approved, jira/valid-reference, lgtm

#248 Fix error: response is string already
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, lgtm

#249 Fix logging tests
  tests/unit/utils/test_logging.py
Labels: approved, lgtm

#252 Correct type for `summary`
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, lgtm

#238 OLS-89: Document config usage
  .gitignore
  README.md
  examples/olsconfig.yaml
  tests/integration/test_feedback.py
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#250 OLS-204: Remove duplicated log msg
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
  ols/src/query_helpers/yaml_generator.py
  ols/src/query_helpers/yes_no_classifier.py
Labels: approved, jira/valid-reference, lgtm

#251 Update QueryDocs docstring
  ols/src/query_helpers/query_docs.py
Labels: approved, lgtm

#253 Update LLMLoader docstring
  ols/src/llms/llm_loader.py
Labels: approved, lgtm

#254 Use default logging level if nothing is specified in config file
  ols/app/models/config.py
  tests/config/config_without_logging.yaml
  tests/unit/test_config.py
  tests/unit/test_models.py
Labels: approved, lgtm

#256 Missing tests for improper URL
  tests/unit/test_config.py
Labels: approved, lgtm
