Repository openshift/lightspeed-service, pull requests merged in 2024-03, with the labels that each got.

#505 Use the correct rag-augmented image in the sample yamls
  .gitignore
  Containerfile
  README.md
  examples/openshift-lightspeed-tls.yaml
  examples/openshift-lightspeed.yaml
  manifests/kustomization.yaml
  manifests/namespace.yaml
  manifests/ols-client-test-rbac.yaml
  manifests/ols-client-test.yaml
  manifests/ols-rbac.yaml
  manifests/ols-redis.yaml
  manifests/ols.yaml
Labels: approved, lgtm

#514 Add path to embedding model to sample config
  examples/openshift-lightspeed-tls.yaml
Labels: approved, lgtm

#520 OLS-58: Link to Jira issue
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#507 Basic metrics endpoint e2e test
  tests/e2e/test_api.py
Labels: approved, lgtm

#510 Default user UID and name for local testing
  ols/constants.py
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#512 Use `object` type instead of `Any`
  ols/app/models/config.py
Labels: approved, lgtm

#511 E2E tests: check query REST API endpoint called with missing and improper payload
  tests/e2e/test_api.py
Labels: approved, lgtm

#523 OLS-364: `llm-loader` is not keyword argument
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
Labels: approved, jira/valid-reference, lgtm

#525 OLS-364: Type fix: response is awaitable
  ols/app/main.py
Labels: approved, jira/valid-reference, lgtm

#527 OLS-364: Fixed all return type hints, so thich check will be possible to enabl…
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/registry.py
Labels: approved, jira/valid-reference, lgtm

#522 OLS-378: Check for proper user UUID
  ols/app/endpoints/ols.py
  ols/src/cache/cache.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#521 OLS-364: Fix runtime error: got multiple values for keyword argument 'llm_params'
  ols/src/query_helpers/question_validator.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#529 OLS-364: Chat prompt constructor based on messages only
  ols/src/prompts/prompts.py
Labels: approved, jira/valid-reference, lgtm

#531 OLS-371: Document more arguments for the e2e-cluster test script
  tests/scripts/test-e2e-cluster.sh
Labels: approved, jira/valid-reference, lgtm

#532 OLS-371: must-gather for e2e script, and install test dep prereqs
  tests/scripts/test-e2e-cluster.sh
  tests/scripts/utils.sh
Labels: jira/valid-reference

#533 OLS-371: export ols token and url for e2e invocation
  tests/scripts/test-e2e-cluster.sh
Labels: jira/valid-reference

#530 OLS-364: Enable call-arg type checks on CI
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#513 OLS-345: configuration in runner.py
  ols/app/main.py
  ols/src/rag_index/index_loader.py
  runner.py
Labels: approved, jira/valid-reference, lgtm

#536 Removed leftover - the dict now has proper type
  ols/src/cache/redis_cache.py
Labels: approved, lgtm

#534 Proper noqa markers (trivial)
  tests/mock_classes/mock_llama_index.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#535 Don't rewrite loop variable inside loop
  tests/integration/test_metrics.py
Labels: approved, lgtm

#537 OLS-378: Use user ID retrieved from auth middleware
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#541 Correct content_hash in pdm.lock
  pdm.lock
Labels: approved, lgtm

#483 OLS-281: Implements azure openai support
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/constants.py
  ols/src/llms/providers/azure_openai.py
  tests/config/singleprovider.e2e.template.config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/llms/providers/test_azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#543 Avoid Ruff warnings: use new invocation command
  Makefile
Labels: approved, lgtm

#544 OLS-283: allow CI to run our e2e against azure openai
  scripts/test-e2e-standalone.sh
  tests/config/singleprovider.e2e.template.config.yaml
Labels: approved, jira/valid-reference, lgtm

#542 Invoke pdm sync to make sure packages are installed according to pmd.lock
  Containerfile
  Makefile
Labels: approved, lgtm

#545 OLS-373: Link to Jira: handling OpenAI-related parameters
  ols/src/llms/providers/openai.py
Labels: approved, jira/valid-reference, lgtm

#540 OLS-301: Setup Matplotlib temporary directory
  runner.py
Labels: approved, jira/valid-reference, lgtm

#551 Fix rag index id to align w/ updated versioned index names
  tests/config/cluster_install/ols_configmap.yaml
  tests/config/singleprovider.e2e.template.config.yaml
Labels: approved, lgtm

#546 OLS-378: User UUID checks in cache implementations
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#548 Avoid possible type error during logging
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#550 OLS-281: pass azure openai model parameters as model_kwargs
  ols/src/llms/providers/azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#553 Vulnerability update: langchain
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#552 Check auth. mechanism in e2e tests
  tests/e2e/test_api.py
Labels: approved, tide/merge-method-squash, lgtm

#554 Update index id refs to use versioned index id
  examples/olsconfig.yaml
  examples/openshift-lightspeed-tls.yaml
Labels: approved, lgtm

#539 Metrics checks in regular REST API calls
  tests/e2e/test_api.py
Labels: approved, lgtm

#557 OLS-378: Caught type errors during UUID checks
  ols/utils/suid.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#559 OLS-398: REST API call checker as context manager
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#558 OLS-398: Specify timeouts for all REST API calls performed in e2e tests
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#562 (Trivial) Don't shadow filter builtin
  ols/utils/query_filter.py
Labels: approved, lgtm

#560 OLS-345: Move config init from configure_hugging_face_envs
  runner.py
Labels: approved, jira/valid-reference, lgtm

#555 OLS-110:added conversation history
  ols/app/endpoints/ols.py
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/redis_cache.py
  ols/src/prompts/prompts.py
  ols/src/query_helpers/chat_history.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#564 Removed Vim package from Redis container file
  Containerfile.redis
Labels: approved, lgtm

#569 Use TypeError not ValueError
  ols/src/llms/providers/registry.py
  tests/unit/llms/providers/test_providers.py
Labels: approved, lgtm

#568 Removed else block: not needed
  ols/app/models/config.py
Labels: approved, lgtm

#570 More readable condition flow
  ols/app/models/config.py
Labels: approved, lgtm

#563 Provide message to `pytest.fail` to be caught and processed by `pytest` tool
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#565 OLS-398: Check duration counters update for all REST API calls
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#571 OLS-58: Ability to select tokenizer
  ols/utils/token_handler.py
Labels: approved, jira/valid-reference, lgtm

#561 OLS-58: Helper method to compute message length
  ols/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#576 `__init__.py` for all unit tests sub-packages
  tests/unit/cache/__init__.py
  tests/unit/docs/__init__.py
  tests/unit/llms/__init__.py
  tests/unit/llms/providers/__init__.py
  tests/unit/query_helpers/__init__.py
  tests/unit/ui/__init__.py
  tests/unit/utils/__init__.py
Labels: approved, lgtm

#577 OLS-230: Script to generate OpenAPI schema + Makefile target to call this script
  Makefile
  scripts/generate_openapi_schema.py
Labels: approved, jira/valid-reference, lgtm

#579 OLS-58: Conversation history won't be None
  ols/app/endpoints/ols.py
Labels: approved, jira/valid-reference, lgtm

#567 OLS-405: Refactor e2e so we can run tests against multiple providers in one shot
  Makefile
  tests/config/cluster_install/ols_configmap.yaml
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
  tests/scripts/test-e2e-cluster.sh
  tests/scripts/test-e2e-standalone.sh
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#581 OLS-230: Pre-generated OpenAPI schema + documentation update
  README.md
  docs/openapi.json
Labels: approved, jira/valid-reference, lgtm

#580 OLS-307 Expose selected model and provider through Prometheus metrics
  ols/app/main.py
  ols/app/metrics/__init__.py
  ols/app/metrics/metrics.py
  tests/integration/test_metrics.py
Labels: approved, lgtm

#582 OSL-230: Check pre-generated OpenAPI schema
  tests/integration/test_openapi.py
Labels: approved, lgtm

#583 OLS-398: Token counter checks in e2e tests
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#556 OLS-81: Team ownership of RAG pipeline - RAG content image
  Containerfile.rag
  Containerfile.rag-content
  scripts/asciidoctor-text/attributes.yaml
  scripts/asciidoctor-text/convert-it-all.py
  scripts/asciidoctor-text/text-converter.rb
  scripts/download_embeddings_model.py
  scripts/generate_embeddings.py
Labels: approved, jira/valid-reference, lgtm

#566 [Bug fix] Add command to keep redis container awake
  Containerfile.redis
Labels: approved, lgtm

#573 OLS-58: Limit conversation history
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#572 Use constants for default responses
  ols/app/endpoints/ols.py
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_api.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, lgtm

#585 OLS-302: Redis commands retry settings
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#587 Disable internal checking of subprocess exit code, it's done explicitly
  scripts/asciidoctor-text/convert-it-all.py
Labels: approved, lgtm

#588 OLS-302: Initialize Redis with retry settings (if provided and enabled)
  ols/src/cache/redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#589 OLS-302: Unit tests: Redis retry settings on Redis client initialization
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#597 Bug fix: marshal and unmarshal messages to be stored in Redis
  ols/src/cache/redis_cache.py
Labels: approved, lgtm

#596 OLS-302: Atomic insert-or-append for one process
  ols/src/cache/redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#600 Stricter Redis mock to avoid errors like OLS-416
  tests/mock_classes/redis.py
Labels: approved, lgtm

#606 Renamed: MockRedisClient
  tests/mock_classes/mock_redis_client.py
  tests/unit/cache/test_cache_factory.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, lgtm

#598 Update docs about adding new provider
  CONTRIBUTING.md
Labels: approved, lgtm

#602 Test for several values using membership test against set
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#603 `limit_conversation_history` is static method
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#604 Bug fix: use opened file as context manager
  scripts/asciidoctor-text/convert-it-all.py
Labels: approved, lgtm

#605 Sorted identifiers in `__all__`
  ols/app/metrics/__init__.py
Labels: approved, lgtm

#607 OLS-302: Redis tests as part of integration tests
  Makefile
  tests/integration/pytest.ini
  tests/integration/test_redis.py
Labels: approved, jira/valid-reference, lgtm

#595 OLS-387: Add user data collection config
  examples/olsconfig.yaml
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#610 Bump-up OpenAI to 1.14.0
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#611 Bump-up devel dependencies: Black
  pdm.lock
Labels: approved, lgtm

#618 OLS-244: Allow model options (fully optional)
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#613 Use shebang for executable script
  scripts/asciidoctor-text/convert-it-all.py
Labels: approved, lgtm

#621 Spacy package as dependency
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#616 Deletes the old/badly named ols service definition.
  examples/openshift-lightspeed-tls.yaml
Labels: approved, lgtm

#622 OLS-244: Better local symbol names
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#601 OLS-365 switch metrics endpoint to FastAPI
  docs/openapi.json
  ols/app/metrics/__init__.py
  ols/app/metrics/metrics.py
  ols/app/routers.py
Labels: approved, lgtm

#623 Update Ruff (devel dependency)
  pdm.lock
Labels: approved, lgtm

#519 OLS-140: Added authorized endpoint to check if the user has permissions to acc…
  docs/openapi.json
  ols/app/endpoints/authorized.py
  ols/app/models/models.py
  ols/app/routers.py
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/unit/app/endpoints/test_authorized.py
Labels: approved, jira/valid-reference, lgtm

#625 Remove trailing slash for metrics route
  README.md
  docs/openapi.json
  ols/app/main.py
  ols/app/metrics/metrics.py
  scripts/generate_openapi_schema.py
  tests/e2e/test_api.py
  tests/integration/test_metrics.py
Labels: approved, lgtm

#626 Refactoring - retrieve user ID
  ols/app/endpoints/ols.py
Labels: approved, lgtm

#630 Add RBAC roles for SAR checking and OLS usage to example setup
  examples/openshift-lightspeed-tls.yaml
Labels: approved, lgtm

#631 Bump-up direct and transitive dependencies
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#628 Fix: cannot raise literal
  scripts/questions_gen.py
Labels: approved, lgtm

#629 Refactoring: use match-case
  scripts/questions_gen.py
Labels: approved, lgtm

#619 OLS-244: Prompt generator
  ols/src/prompts/prompt_generator.py
  ols/src/query_helpers/docs_summarizer.py
  tests/unit/prompts/__init__.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, jira/valid-reference, lgtm

#633 Remove unused kw file constant
  ols/app/endpoints/ols.py
  ols/constants.py
Labels: approved, lgtm

#549 OLS-165: Response sanity check
  scripts/validate_response.py
  tests/e2e/test_api.py
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#638 Update Watson libs and its dependencies
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#641 Refactoring: argparser type don't have to be callabke
  scripts/validate_response.py
Labels: approved, lgtm

#642 Refactoring: moved expression out of the loop
  scripts/asciidoctor-text/convert-it-all.py
Labels: approved, lgtm

#644 Refactoring: use dict constructor
  scripts/generate_embeddings.py
Labels: approved, lgtm

#538 OLS-135: feedback storage
  docs/openapi.json
  ols/app/endpoints/feedback.py
  ols/app/models/config.py
  ols/app/models/models.py
  tests/config/cluster_install/ols_configmap.yaml
  tests/config/cluster_install/ols_manifests.yaml
  tests/config/singleprovider.e2e.template.config.yaml
  tests/e2e/test_api.py
  tests/integration/test_feedback.py
  tests/scripts/test-e2e-standalone.sh
  tests/unit/app/endpoints/test_feedback.py
  tests/unit/app/models/test_config.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#639 Updated Ruff as devel dependency
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#640 OLS-440: Postgres configuration
  ols/app/models/config.py
  ols/constants.py
  ols/src/cache/cache_factory.py
  ols/src/cache/postgres_cache.py
  tests/config/postgres_cert.crt
  tests/config/postgres_password.txt
  tests/config/valid_config_postgres.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#645 OLS-437: Expose model and provider metrics
  ols/app/main.py
  ols/app/metrics/__init__.py
  ols/app/metrics/metrics.py
  tests/config/valid_config.yaml
  tests/e2e/test_api.py
  tests/integration/test_metrics.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#649 Refactoring: not too nested logic flow
  ols/app/models/config.py
Labels: approved, lgtm

#648 OLS-437: Model settings metrics tests
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#647 Refactoring: use `dict` constructor
  scripts/questions_gen.py
Labels: approved, lgtm

#651 Refactoring: `else` block not needed
  ols/src/ui/gradio_ui.py
Labels: approved, lgtm

#653 Remove rag testing from standalone.sh execution
  scripts/download_embeddings_model.py
  tests/config/singleprovider.e2e.template.config.yaml
  tests/e2e/test_api.py
  tests/scripts/test-e2e-standalone.sh
Labels: approved, lgtm

#654 OSL-363: Bug fix: fixed provider unit tests
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, lgtm

#632 OLS-81: switchover to CI-built RAG; OLS-355: Faiss
  Containerfile.rag
  Containerfile.rag-content
  Makefile
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/rag_index/index_loader.py
  scripts/asciidoctor-text/attributes.yaml
  scripts/asciidoctor-text/text-converter.rb
  tests/config/cluster_install/ols_configmap.yaml
  tests/e2e/test_api.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/rag_index/test_index_loader.py
Labels: approved, jira/valid-reference, lgtm

#660 (Trivial) Correct provider names
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, lgtm

#662 OLS-420: Bump-up pytest-cov version (devel library)
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#661 Stricter type checking in `prompt_generator.py`
  ols/src/prompts/prompt_generator.py
Labels: approved, lgtm

#659 OLS-447: Added TODO: refactoring params from QuestionValidator
  ols/src/query_helpers/question_validator.py
Labels: approved, jira/valid-reference, lgtm

#652 OLS-434: e2e test - load QnA from file
  scripts/validate_response.py
  tests/e2e/conftest.py
  tests/e2e/test_api.py
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#665 e2e trivial fix: Check for conversation ID in JSON response
  tests/e2e/test_api.py
Labels: approved, lgtm

#658 OLS-338: Add docs_url metadata element while creating embedding index
  Containerfile.rag
  Makefile
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  tests/constants.py
  tests/mock_classes/mock_query_engine.py
  tests/mock_classes/mock_retrievers.py
  tests/unit/docs/test_doc_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#666 Move towards a single ols image that includes rag
  Containerfile
  Containerfile.rag
Labels: approved, lgtm

#650 OLS-363: Provider parameters check
  ols/src/llms/providers/provider.py
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_openai.py
Labels: approved, jira/valid-reference, lgtm

#670 OLS-363: Now parameters don't have to be fixed in provider classes
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/openai.py
Labels: approved, jira/valid-reference, lgtm

#669 OLS-420: updated all non-devel dependencies
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#672 Add latest vec db folder to gitignore/example
  .gitignore
  examples/olsconfig.yaml
  examples/openshift-lightspeed-tls.yaml
Labels: approved, lgtm

#674 Uvicorn log level settings
  examples/olsconfig.yaml
  ols/app/models/config.py
  runner.py
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#668 OLS-74: Align OLS+RAG on the same approved embedding model
  ols/constants.py
  ols/src/rag_index/index_loader.py
  scripts/asciidoctor-text/convert-it-all.py
  scripts/download_embeddings_model.py
  scripts/generate_embeddings.py
  scripts/questions_gen.py
  scripts/validate_response.py
  tests/e2e/test_api.py
  tests/unit/rag_index/test_index_loader.py
Labels: approved, jira/valid-reference, lgtm

#663 OLS-214: Add transcripts capture configuration
  examples/olsconfig.yaml
  ols/app/models/config.py
  tests/config/cluster_install/ols_configmap.yaml
  tests/config/singleprovider.e2e.template.config.yaml
  tests/scripts/test-e2e-standalone.sh
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#675 Convert e2e test script logic into python code
  tests/e2e/cluster_utils.py
  tests/e2e/consts.py
  tests/e2e/metrics_utils.py
  tests/e2e/test_api.py
  tests/e2e/test_utils.py
  tests/scripts/test-e2e-standalone.sh
  tests/scripts/utils.sh
Labels: approved, tide/merge-method-squash, lgtm

#664 OLS-434: Pass arguments to e2e
  Makefile
  tests/e2e/conftest.py
  tests/e2e/consts.py
  tests/e2e/test_api.py
  tests/scripts/utils.sh
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm
