Repository openshift/lightspeed-service, pull requests merged in 2024-05, with the labels that each got.

#852 Proper return type (fix)
  scripts/feedback_aggregator.py
Labels: approved, lgtm

#851 Return value fix
  tests/e2e/cluster_utils.py
Labels: approved, lgtm

#854 Add junit reporting for ols setup failures
  tests/scripts/utils.sh
Labels: approved, lgtm

#855 Just set global variable type, don't initialize to silly value
  tests/e2e/test_api.py
Labels: approved, lgtm

#853 Check that query redactor is constructed before accessing it's attribute
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#856 Don't use magic constant in tests
  tests/scripts/validate_response.py
Labels: approved, lgtm

#857 OLS-447: Check global provider configuration existence
  ols/src/llms/llm_loader.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, jira/valid-reference, lgtm

#858 OLS-527: bump up libs
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#860 increase l2 threshold cut-off
  ols/constants.py
Labels: approved, lgtm

#846 OLS-506: Remove standalone script
  Makefile
  tests/e2e/pytest.ini
  tests/scripts/test-e2e-cluster.sh
  tests/scripts/test-e2e-standalone.sh
Labels: approved, jira/valid-reference, lgtm

#862 Save CI response eval job result
  Makefile
  tests/scripts/utils.sh
  tests/scripts/validate_response.py
Labels: approved, lgtm

#861 OLS-259: Use filepath instead of raw string
  ols/app/models/config.py
Labels: approved, jira/valid-reference, lgtm

#867 Fix logging in the number of attempts
  tests/scripts/utils.sh
Labels: approved, lgtm

#866 Fixed unit test
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#847 OLS-447: LLM parameters mapping
  ols/constants.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/provider.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  tests/mock_classes/mock_llm_loader.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/query_helpers/test_query_helper.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#864 Update quay references to use the openshift-lightspeed org
  Containerfile
  Makefile
  README.md
  examples/openshift-lightspeed-tls.yaml
  scripts/build-container.sh
Labels: approved, lgtm

#863 OLS-423: use a generic message for rejecting non-openshift questions
  ols/constants.py
Labels: approved, jira/valid-reference, lgtm

#871 Don't reuse the same variable for different purposes
  tests/e2e/cluster_utils.py
Labels: approved, lgtm

#873 OLS-582: Don't pass ServiceContext
  scripts/questions_gen.py
Labels: approved, jira/valid-reference, lgtm

#878 List of documents is no longer optional (API we call has changed)
  ols/src/query_helpers/query_docs.py
Labels: approved, lgtm

#876 Avoid NPE when metric is not parseable
  tests/e2e/metrics_utils.py
Labels: approved, lgtm

#823 OLS-506: must-gather in tests
  tests/e2e/cluster_utils.py
  tests/e2e/test_api.py
  tests/scripts/must_gather.py
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#879 OLS-586: Exclude parameter is of type set
  ols/app/endpoints/feedback.py
Labels: approved, jira/valid-reference, lgtm

#881 Added missing `return` statement
  tests/e2e/cluster_utils.py
Labels: approved, lgtm

#883 Use `Path` value properly in tests
  tests/integration/test_ols.py
Labels: approved, lgtm

#884 Refactoring: MockRetrievedNode
  tests/mock_classes/mock_retrieved_node.py
  tests/mock_classes/mock_retrievers.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#880 OLS-589: Specify host in all cases
  runner.py
  tests/unit/utils/__init__.py
Labels: approved, jira/valid-reference, lgtm

#885 Fix: Remove default test tags
  Makefile
Labels: approved, lgtm

#886 Script to list objects stored in Ceph bucket
  scripts/list_objects_in_ceph.py
Labels: approved, lgtm

#887 Ignore __pypackages__ directory
  .gitignore
Labels: approved, lgtm

#891 Abstractproperty decorator is deprecated, use property+abstractmethod
  ols/src/llms/providers/provider.py
Labels: approved, lgtm

#893 Watsonxllm mock class should have method headers compatible with real WatsonxLLM class
  tests/mock_classes/mock_watsonxllm.py
Labels: approved, lgtm

#894 Fixed type: frozenset is not compatible with set
  ols/app/main.py
Labels: approved, lgtm

#890 OLS-591: ignore cluster used by CCX checking infrastructure
  scripts/feedback_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#892 Fixtures for authorization
  tests/integration/test_authorized.py
Labels: approved, lgtm

#874 Use proper in memory cache config class name
  ols/app/models/config.py
  ols/constants.py
  ols/src/cache/cache_factory.py
  ols/src/cache/in_memory_cache.py
  tests/unit/app/models/test_config.py
  tests/unit/cache/test_cache_factory.py
  tests/unit/cache/test_in_memory_cache.py
Labels: approved, lgtm

#899 Fix: metrics_app does not exists anymore
  ols/app/metrics/__init__.py
Labels: approved, lgtm

#897 OLS-598: Data collection scripts in separate directory
  scripts/data_collection/README.md
  scripts/data_collection/list_objects_in_ceph.py
  scripts/data_collection/user_data_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#900 OLS-598: Script to download object from Ceph
  scripts/data_collection/README.md
  scripts/data_collection/download_ols_archive.py
Labels: approved, jira/valid-reference, lgtm

#870 Print e2e tests durations
  Makefile
Labels: approved, lgtm

#898 Add missing field in schema for LLMResponse
  docs/openapi.json
  ols/app/models/models.py
Labels: approved, lgtm

#902 OSL-598: Allow spaces in cluster list
  scripts/data_collection/user_data_aggregator.py
Labels: approved, lgtm

#903 OLS-598: Script to delete OLS archive from Ceph bucket
  scripts/data_collection/README.md
  scripts/data_collection/delete_ols_archive.py
Labels: approved, jira/valid-reference, lgtm

#904 Added TODO for OLS-606 found in the script question_gen.py
  scripts/questions_gen.py
Labels: approved, lgtm

#906 Remove unreachable return from postgres cache
  ols/src/cache/postgres_cache.py
Labels: approved, lgtm

#911 Fix: `dockerconfig` technically is unbound variable in circumstances when `TypeError` is thrown from different statement
  ols/user_data_collection/data_collector.py
Labels: approved, lgtm

#907 OLS-551: Remove langchain messages objects in favor of simple dicts
  ols/app/endpoints/ols.py
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/postgres_cache.py
  ols/src/cache/redis_cache.py
  ols/src/query_helpers/chat_history.py
  tests/integration/test_redis.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_postgres_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#908 Type fix: attributes won't be `None` in runtime
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#909 "None" (string) are not special values to be checked for auth. attributes
  ols/utils/auth_dependency.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#915 OLS-595: Prolong wait interval for data collector in e2e test
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#912 `yaml_port` is used in `raise` block so it need to be defined outside `try` block
  ols/app/models/config.py
Labels: approved, lgtm

#913 Better retry logic for flaky end-to-end tests
  tests/e2e/test_decorators.py
Labels: approved, lgtm

#914 TODO with OLS-619
  scripts/questions_gen.py
Labels: approved, lgtm

#895 OLS-473: Chunk collected user data to archives
  ols/user_data_collection/data_collector.py
  tests/e2e/test_api.py
  tests/unit/user_data_collection/test_data_collector.py
Labels: approved, tide/merge-method-squash, jira/valid-reference, lgtm

#919 Full type specification for conversation history
  ols/app/endpoints/ols.py
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/postgres_cache.py
  ols/src/cache/redis_cache.py
Labels: approved, lgtm

#920 OLS-626: Script to upload CSV files into Google sheet
  scripts/data_collection/README.md
  scripts/data_collection/update_google_sheet.py
Labels: approved, jira/valid-reference, lgtm

#925 Fix OLS-596: timeout in BAM provider
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#918 Re-enable BAM for e2e testing
  tests/scripts/test-e2e-cluster.sh
Labels: approved, lgtm

#921 OLS-493: Change score as per faiss IP index
  Containerfile
  Makefile
  ols/constants.py
  ols/utils/token_handler.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#929 Add tip for local e2e testing
  CONTRIBUTING.md
Labels: approved, lgtm

#927 OLS-570: log test stage in case of any detected error
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#931 OLS-570: Check schema against pre-generated one
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#930 OLS-570: Fix unexpected and random 503 HTTP failures accessing openapi.json
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#935 Don't use pickle module, now it is possible to use simple JSON
  ols/src/cache/postgres_cache.py
  ols/src/cache/redis_cache.py
  tests/e2e/test_api.py
  tests/unit/cache/test_postgres_cache.py
Labels: approved, lgtm

#933 Fixture with OLS configuration used in unit tests + use Path object as expected
  tests/unit/rag_index/test_index_loader.py
Labels: approved, lgtm

#937 Added Bandit as devel dependencies
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#938 Type safer working with list of messages
  ols/app/endpoints/ols.py
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/postgres_cache.py
  ols/src/cache/redis_cache.py
Labels: approved, lgtm

#940 OLS-583: Bump-up FastAPI and GradIO libraries
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#941 OLS-612: Mock all methods for mock vector store
  tests/mock_classes/mock_retrievers.py
Labels: approved, jira/valid-reference, lgtm

#946 OLS-583: Update dependencies for week #20
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#947 Fix: added missing shebang
  scripts/data_collection/update_google_sheet.py
Labels: approved, lgtm

#944 Fix: history passed to chat UI can not be None
  tests/unit/ui/test_gradio_ui.py
Labels: approved, lgtm

#945 Makefile target to run bandit + updated documentation + updated PDM commands
  CONTRIBUTING.md
  Makefile
  pyproject.toml
Labels: approved, lgtm

#839 OLS-503: Fine-tune system prompt
  ols/src/prompts/prompts.py
  tests/config/valid_config.yaml
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#948 added timestamp to feedback endpoint (OLS-616)
  ols/app/endpoints/feedback.py
  tests/unit/app/endpoints/test_feedback.py
Labels: approved, ok-to-test, lgtm

#943 OLS-379: Refactor configuration
  ols/__init__.py
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
  ols/app/main.py
  ols/app/metrics/metrics.py
  ols/app/models/config.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/provider.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  ols/utils/auth_dependency.py
  ols/utils/config.py
  ols/utils/query_filter.py
  runner.py
  scripts/generate_openapi_schema.py
  scripts/questions_gen.py
  tests/config/auth_config.yaml
  tests/integration/conftest.py
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_openapi.py
  tests/unit/app/endpoints/test_authorized.py
  tests/unit/app/endpoints/test_feedback.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_config.py
  tests/unit/conftest.py
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_openai.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/query_helpers/test_query_helper.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/rag_index/test_index_loader.py
  tests/unit/user_data_collection/test_data_collector.py
  tests/unit/utils/test_auth_dependency.py
  tests/unit/utils/test_config.py
  tests/unit/utils/test_query_filter.py
Labels: approved, jira/valid-reference, lgtm

#950 OLS-583: Update OpenAI and langchain-openai libraries
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#949 OLS-622: Provider config refactoring
  ols/app/models/config.py
Labels: approved, jira/valid-reference, lgtm

#955 Main config attributes are not optional anymore
  ols/app/models/config.py
Labels: approved, lgtm

#951 OLS-631: Use buildin dict in typing
  ols/app/models/models.py
Labels: approved, jira/valid-reference, lgtm

#958 Added TODO for OLS-648 + one simple fix for empty path check
  ols/utils/auth_dependency.py
Labels: approved, lgtm

#936 #OLS-451 added woke rules and fixed inclusive-naming incompatabilities
  .gitignore
  .woke.yaml
  Makefile
  ols/src/query_helpers/docs_summarizer.py
  tests/scripts/utils.sh
Labels: approved, lgtm

#956 Fix type for AppConfig
  ols/app/metrics/metrics.py
Labels: approved, lgtm

#957 Explicit response metadata type specifications
  ols/app/endpoints/authorized.py
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
Labels: approved, lgtm

#960 Ignore false type errors or errors that can't be fixed due to missing type hints
  ols/app/metrics/metrics.py
  ols/src/cache/redis_cache.py
  ols/src/rag_index/index_loader.py
Labels: approved, lgtm

#953 OLS-622: provider-specific configuration
  ols/app/models/config.py
  tests/config/valid_config_with_azure_openai.yaml
  tests/config/valid_config_with_azure_openai_api_version.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#962 Better Bandit configuration
  Makefile
  pyproject.toml
Labels: approved, lgtm

#959 Add snyk exclusions for test code
  .snyk
Labels: approved, lgtm

#965 OLS-654: proper error messages for missing sections in olsconfig.yaml
  ols/app/models/config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#961 Use latest rag content
  Containerfile
  Makefile
Labels: approved, lgtm

#969 Add more snyk exclusions
  .snyk
Labels: approved, lgtm

#970 OLS-583: Bump-up langchain-ibm to 0.1.7
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#971 Updated langchain-core and llama-index
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#954 OLS-631: Switch ReferencedDocument from BaseModel to dataclass
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#967 OLS-622: Provider specific base class
  ols/app/models/config.py
  tests/config/valid_config_with_bam.yaml
  tests/config/valid_config_with_watsonx.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#972 OLS-657: TODO about bump-up langchain to version 0.2.0
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#976 OLS-622: Forbid unknown provider-specific parameters
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#977 OLS-622: Provider specific parameters take precedence over regular parameters
  ols/src/llms/providers/azure_openai.py
  tests/config/secret2.txt
  tests/unit/llms/providers/test_azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#980 OLS-622: Don't need to explicitly specify default None value
  ols/app/models/config.py
Labels: approved, jira/valid-reference, lgtm

#975 (Trivial) simplify mock retrievers class
  tests/mock_classes/mock_retrievers.py
Labels: approved, lgtm

#979 OLS-550: Use f-strings instead of str.format()
  scripts/data_collection/list_objects_in_ceph.py
Labels: approved, jira/valid-reference, lgtm

#982 OLS-622: provider-specific config for other providers (not just Azure OpenAI)
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/watsonx.py
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_openai.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, jira/valid-reference, lgtm

#981 Fix: leftover string literals in e2e tests
  tests/e2e/test_api.py
Labels: approved, lgtm

#952 OLS-631: Rag in transcript
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
  scripts/data_collection/user_data_aggregator.py
  tests/e2e/test_api.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#986 OLS-510: minor updates in code
  scripts/data_collection/__init__.py
  scripts/data_collection/user_data_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#983 OLS-661: Fix tar related vulnerability issues found by Snyk
  scripts/data_collection/user_data_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#984 Ignore Snyk cache files
  .gitignore
Labels: approved, lgtm

#987 OLS-641: URL and credentials are part of provider objects
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/openai.py
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_openai.py
Labels: approved, jira/valid-reference, lgtm

#991 OLS-622: check for credentials
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/watsonx.py
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, jira/valid-reference, lgtm

#985 OLS-488: Cache conversation_cache in config singleton
  ols/utils/config.py
Labels: approved, jira/valid-reference, lgtm

#993 OLS-641: fix - proper type conversion
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/openai.py
Labels: approved, jira/valid-reference, lgtm

#999 OLS-641: Add azure-identity package that is needed by Azure OpenAI auth mechanism
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#966 OLS-492: Combine response evaluation with e2e
  Makefile
  tests/e2e/conftest.py
  tests/e2e/constants.py
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
  tests/scripts/utils.sh
  tests/scripts/validate_response.py
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#1002 OLS-641: Access token retrieval code
  ols/src/llms/providers/azure_openai.py
  tests/unit/llms/providers/test_azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#1003 OLS-641: Added missing unit test
  ols/src/llms/providers/azure_openai.py
  tests/unit/llms/providers/test_azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#1006 Bump-up Ruff to version 0.4.6
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#989 OLS-488: Refactor /liveness endpoint
  docs/openapi.json
  ols/app/endpoints/health.py
  ols/app/models/models.py
  tests/e2e/test_api.py
  tests/integration/test_liveness_readiness.py
  tests/unit/app/endpoints/test_health.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm
