Repository openshift/lightspeed-service, pull requests merged in 2024-09, with the labels that each got.

#1513 OLS-757: Increase volume for prefetch build
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1515 OLS-757: PDM is direct dependency, so it can be installed by pip in hermetic b…
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1519 OLS-985: Support for RHOAI VLLM provider in configuration
  ols/app/models/config.py
  ols/constants.py
  tests/benchmarks/test_prompt_generator.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1518 OLS-757: Updated list of packages for Cachi2
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1517 eval: increase consistency cut-off for openai
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, lgtm

#1526 Fixed comments for RHOAI VLLM-specific unit tests
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1527 OLS-985: Info about RHELAI + added it into example configuration
  README.md
  examples/olsconfig.yaml
Labels: approved, jira/valid-reference, lgtm

#1530 OLS-985: Updated doc about RHELAI
  README.md
Labels: approved, jira/valid-reference, lgtm

#1529 OLS-985: RHELAI VLLM as provider for OLS
  ols/src/llms/providers/provider.py
  ols/src/llms/providers/rhelai_vllm.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/providers/test_rhelai_vllm.py
Labels: approved, jira/valid-reference, lgtm

#1512 increase max resp token default to 1024
  README.md
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1532 OLS-985: Updated config file for integration tests
  tests/config/config_for_integration_tests.yaml
Labels: approved, jira/valid-reference, lgtm

#1499 Removed sbom-json-check task from Konflux pipelines
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1534 Bump-up pytest-asyncio to 0.24.0
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1528 eval: add alternate eval3 ans for openai
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, lgtm

#1535 OLS-1008: Fix CVE: bump-up cryptography to 43.0.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1536 Bump-up fastapi
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1537 OLS-1008: Fixed CVE in package list of Cachi2
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1545 Refactor: disable meaningless warnings
  tests/benchmarks/test_attachment_appender.py
  tests/benchmarks/test_docs_summarizer.py
  tests/benchmarks/test_prompt_generator.py
  tests/benchmarks/test_redactor.py
Labels: approved, lgtm

#1547 Fixed README.md rendering
  README.md
Labels: approved, lgtm

#1540 Removed f-strings from logging
  scripts/data_collection/user_data_aggregator.py
Labels: approved, lgtm

#1549 OLS-757: Enable prefetch build for the service
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1548 readme - typo fix
  README.md
Labels: approved, lgtm

#1543 Bump-up ibm-watsonx-ai to 1.1.8
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1541 Refactoring: follow happy path: removed else blocks that are not needed
  ols/app/endpoints/health.py
Labels: approved, lgtm

#1542 Refactor: use class pattern in pattern matching
  ols/utils/errors_parsing.py
Labels: approved, lgtm

#1551 Add olsconfig sample for local ollama server
  examples/olsconfig-local-ollama.yaml
Labels: approved, ok-to-test, lgtm

#1554 Refactoring: remove global variable reference
  tests/e2e/utils/postgres.py
Labels: approved, lgtm

#1555 Refactoring: lazy docstring format in token handler code
  ols/utils/token_handler.py
Labels: approved, lgtm

#1557 Bump-up prefetch dependencies task
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1556 Documentation: mention local ollama server
  README.md
Labels: approved, lgtm

#1546 eval: eval script refactoring
  scripts/evaluation/driver.py
  scripts/evaluation/response_evaluation.py
  tests/e2e/conftest.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#1558 Refactoring: use build-in standard function, not special method
  tests/e2e/utils/decorators.py
Labels: approved, lgtm

#1560 OLS-1031: Bump-up buildah-8g
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1559 Documentation: hermetic build flow
  docs/hermetic_build.png
Labels: approved, lgtm

#1561 OLS-1031: Use buildah-10g
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1562 OLS-1032: Bump-up Torch to 2.4.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1573 OLS-1030: Override limits for build-source-image task
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1574 OLS-1044: Fix vulnerability in zipp package
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1576 OLS-1051: Fix CVE in jinja2 package version 3.1.3
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1569 OLS-1004: Use single default value for context window
  ols/app/models/config.py
  ols/constants.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1581 Refactoring: don't import config on toplevel
  ols/__init__.py
  runner.py
Labels: approved, lgtm

#1579 OLS-1052: Fix CVE in scikit-learn package
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1577 eval: cutoff increase for eval6 - openai
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, lgtm

#1583 Refactoring + fix: Proper status checks
  tests/unit/utils/test_errors_parsing.py
Labels: approved, lgtm

#1584 OLS-1032: Bump-up langchain to 0.2.16
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1588 Refactoring: lazy log formatting in redactor.py
  ols/utils/redactor.py
Labels: approved, lgtm

#1589 OLS-1015: Store certificate path
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1591 OLS-1015: Use provider with defined HTTP client with certificates
  ols/src/llms/providers/rhelai_vllm.py
  ols/src/llms/providers/rhoai_vllm.py
  tests/unit/llms/providers/test_rhelai_vllm.py
  tests/unit/llms/providers/test_rhoai_vllm.py
Labels: approved, jira/valid-reference, lgtm

#1592 OLS-1032: Bump-up langchain community to 0.2.16
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1594 OLS-1032: Bump-up aiohttp to version 3.10.5
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1595 Updated prefetch package list
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, lgtm

#1597 OLS-1032: Bump-up certify package to 2024.7.30
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1598 Trivial refactor: constants in uppercase
  scripts/upload_artifact_s3.py
Labels: approved, lgtm

#1600 Updated arch diagram: add auth.check block
  docs/architecture_diagram.png
  docs/architecture_diagram.uml
Labels: approved, lgtm

#1582 eval: options for just model/param/prompt/rag
  scripts/evaluation/README.md
  scripts/evaluation/driver.py
  scripts/evaluation/response_evaluation.py
  scripts/evaluation/utils.py
  tests/e2e/conftest.py
Labels: approved, lgtm

#1603 OLS-1032: Bump-up Uvicorn to version 0.30.6
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1612 OLS-1032: Bump-up FastAPI to 0.114.2
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1604 Refactoring: removed letfover
  ols/src/llms/providers/provider.py
Labels: approved, lgtm

#1616 Better program logic
  ols/src/prompts/prompt_generator.py
Labels: approved, lgtm

#1617 Better program logic in Postgres interface
  ols/src/cache/postgres_cache.py
Labels: approved, lgtm

#1618 Info about package update and lockfile
  CONTRIBUTING.md
Labels: approved, lgtm

#1615 OLS-1032: Bump-up Pydantic
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1620 Make cache content a binary buffer before insertion into a bytea field in Postgres
  ols/src/cache/postgres_cache.py
  tests/unit/cache/test_postgres_cache.py
Labels: approved, lgtm

#1614 eval: refactoring
  scripts/evaluation/response_evaluation.py
  scripts/evaluation/utils/__init__.py
  scripts/evaluation/utils/constants.py
  scripts/evaluation/utils/models.py
  scripts/evaluation/utils/plot.py
  scripts/evaluation/utils/rag.py
  scripts/evaluation/utils/response.py
  scripts/evaluation/utils/score.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#1623 OLS update version to 0.1.6
  docs/openapi.json
  ols/app/main.py
Labels: approved, lgtm

#1628 Info about local deployment
  README.md
Labels: approved, lgtm

#1626 Keep exception context when raising new one
  ols/app/models/config.py
Labels: approved, lgtm

#1625 Placeholder instead of unused variable
  tests/e2e/utils/cluster.py
Labels: approved, lgtm

#1632 OLS-1080: Fix OLS-1080
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1633 Trivial: specify `maxsplit` value
  tests/e2e/utils/decorators.py
Labels: approved, lgtm

#1637 Updated cachi2 packages
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, lgtm

#1638 Updated pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#1643 OLS-1085: Install PDM 2.18.1
  Makefile
Labels: approved, jira/valid-reference, lgtm

#1639 Note about auth.
  README.md
Labels: approved, lgtm

#1644 OLS-1085: Install correct PDM version
  Containerfile
Labels: approved, lgtm

#1654 OLS-86: Intro structure with providers info
  README.md
Labels: approved, jira/valid-reference, lgtm

#1655 OLS-86: Info how to get API key to LLM
  README.md
Labels: approved, jira/valid-reference, lgtm

#1656 OLS-86: Correct info about providers
  README.md
Labels: approved, jira/valid-reference, lgtm

#1657 OLS-86: Overall service architecture
  README.md
Labels: approved, jira/valid-reference, lgtm

#1659 OLS-1065: fix e2e test to pull unreleased component images
  tests/config/operator_install/imagedigestmirrorset.yaml
  tests/e2e/test_api.py
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#1634 Change to `registry.redhat.io`
  Containerfile
Labels: approved, lgtm

#1647 OLS-1082: Fixed issue OLS-1082
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1660 OLS-86: Component integration diagram
  docs/component_integration.png
Labels: approved, jira/valid-reference, lgtm

#1646 OLS-1085: Show PDM version on CI
  Makefile
Labels: approved, jira/valid-reference, lgtm

#1641 Refactoring: better exception context
  ols/src/cache/postgres_cache.py
Labels: approved, lgtm

#1663 OLS-86: Doc about cache
  README.md
Labels: approved, jira/valid-reference, lgtm

#1648 Wait longer for getting clusterversion
  tests/e2e/test_api.py
Labels: approved, lgtm

#1664 OLS-1088: More verbose e2e tests setup + increased `oc` command wait time
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#1571 OLS-888: Install operator from bundle
  tests/config/operator_install/catalog.yaml
  tests/config/operator_install/operatorgroup.yaml
  tests/config/operator_install/subscription.yaml
  tests/e2e/test_api.py
  tests/scripts/test-e2e-cluster.sh
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#1666 Updated packages to prefetch
  requirements-build.in
  requirements.txt
Labels: approved, lgtm

#1671 Better import
  runner.py
Labels: approved, lgtm

#1672 Refactor: simpler program logic
  tests/mock_classes/mock_k8s_api.py
Labels: approved, lgtm

#1674 OLS-1001: Command line args to process special packages
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#1675 OLS-86: Some grammar fixes
  README.md
Labels: approved, jira/valid-reference, lgtm

#1676 OLS-1001: Ability to specify work directory
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#1586 OLS-992: Add Entra ID test
  ols/app/metrics/metrics.py
  tests/config/operator_install/olsconfig.crd.azure_openai.yaml
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
  tests/scripts/test-e2e-cluster.sh
Labels: approved, lgtm

#1677 Bump-up SQLAlchemy to fix prefetch build task
  pdm.lock
  pyproject.toml
Labels: approved, lgtm
