Repository openshift/lightspeed-service, pull requests merged in 2024-07, with the labels that each got.

#1184 Add azure_ad_token as valid parameter
  ols/src/llms/providers/provider.py
Labels: approved, lgtm

#1193 Use colon when specifying rule code
  ols/constants.py
  scripts/generate_packages_to_prefetch.py
  tests/mock_classes/mock_llm_chain.py
  tests/unit/app/models/test_config.py
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#1192 OLS-779: Bump-up OpenAI to version 1.31.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1199 OLS-779: Bump-up llama_index_embeddings_huggingface to 0.2.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1195 Removed now-unused type check disable flags
  ols/app/endpoints/ols.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/openai.py
Labels: approved, lgtm

#1197 Enable new pygrep-hooks rules
  ols/src/rag_index/index_loader.py
  pyproject.toml
Labels: approved, lgtm

#1198 No global skips for Bandit security checks
  ols/constants.py
  pyproject.toml
  runner.py
Labels: approved, lgtm

#1201 TLS settings itself is not optional - but it's attributes are
  ols/app/models/config.py
Labels: approved, lgtm

#1207 fix test case with sample attachment - pass query_val
  tests/e2e/test_api.py
Labels: approved, lgtm

#1209 OLS-779: Bump-up lanchchain-ibm to 0.1.9
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1200 Simpler logging config init
  tests/e2e/conftest.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1210 Refactor: client-utils and response-utils
  tests/e2e/test_api.py
  tests/e2e/utils/client.py
  tests/e2e/utils/response.py
Labels: approved, lgtm

#1191 OLS-409: Evaluation - standalone script & f1 score
  .snyk
  pdm.lock
  pyproject.toml
  scripts/evaluation/README.md
  scripts/evaluation/__init__.py
  scripts/evaluation/driver.py
  scripts/evaluation/response_evaluation.py
  tests/e2e/conftest.py
  tests/e2e/test_api.py
  tests/e2e/utils/constants.py
Labels: approved, jira/valid-reference, lgtm

#1159 OLS-697: Add CacheEntry model
  ols/app/endpoints/ols.py
  ols/app/models/models.py
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/postgres_cache.py
  ols/src/cache/redis_cache.py
  tests/integration/test_redis.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_postgres_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, tide/merge-method-squash, jira/valid-reference, lgtm

#1213 TLSConfig loading unit tests
  tests/config/key
  tests/config/password
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1211 Added unit test to check if ReferencedDocuments can be deserialized from string containing JSON
  tests/unit/app/models/test_models.py
Labels: approved, lgtm

#1215 OLS-805: CVE-free certifi package
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1219 Switch to azure gpt35-16k for ci e2e
  tests/scripts/test-e2e-cluster.sh
Labels: approved, lgtm

#1212 OLS-779: Bump-up OpenAI to version 1.35.7
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1218 OLS-809: Migrate to Watsonx AI
  ols/src/llms/providers/provider.py
  ols/src/llms/providers/watsonx.py
  pdm.lock
  pyproject.toml
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, jira/valid-reference, lgtm

#1222 OLS-547: Info about Azure OpenAI alternative creds. settings
  README.md
Labels: approved, jira/valid-reference, lgtm

#1221 OLS-547: Removed now-unsupported config
  tests/config/valid_config_with_azure_openai_tenant_and_client_id.yaml
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1223 Evaluation - Add 30 per topic QnAs
  .gitignore
  scripts/evaluation/driver.py
  scripts/evaluation/eval_data/interview_qna_30_per_title.parquet
  scripts/evaluation/eval_data/question_answer_pair.json
  scripts/evaluation/response_evaluation.py
  tests/e2e/conftest.py
Labels: approved, lgtm

#1224 OLS-804: Prepare for new Ruff version
  pdm.lock
  pyproject.toml
  scripts/evaluation/driver.py
  tests/e2e/utils/client.py
  tests/e2e/utils/cluster.py
Labels: approved, jira/valid-reference, lgtm

#1225 Complex config for integration tests
  tests/config/config_for_integration_tests.yaml
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_openapi.py
Labels: approved, lgtm

#1227 Add script to get rag chunks for spot verification
  scripts/evaluation/query_rag.py
Labels: approved, lgtm

#1228 OLS-779: Bump-up Pydantic to version 2.8.2
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1233 Simpler and more modern superclass constructor call
  ols/utils/config.py
Labels: approved, lgtm

#1238 OLS-832: SQLAlchemy must be up to date to generate hashes properly
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1240 Updated package references for Cachi2
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, lgtm

#1237 OLS-832: Fix build script
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#1239 OLS-821: Update labels for EC
  Containerfile
Labels: approved, jira/valid-reference, lgtm

#1241 Change rule name according to updated Ruff naming
  pyproject.toml
Labels: approved, lgtm

#1243 OLS-598: Script to print bucket ACLs
  scripts/data_collection/README.md
  scripts/data_collection/print_acls.py
Labels: approved, jira/valid-reference, lgtm

#1242 Minor refactoring + increase LLM call retry count
  scripts/evaluation/response_evaluation.py
Labels: approved, lgtm

#1244 OLS-703: Script to print EC failures
  scripts/print_ec_failures.py
Labels: approved, jira/valid-reference, lgtm

#1216 OLS-650: Ability to add additional CA certs
  README.md
  ols/app/models/config.py
  pdm.lock
  pyproject.toml
  runner.py
  tests/unit/app/models/test_config.py
  tests/unit/extra_certs/sample_cert_1.crt
  tests/unit/extra_certs/sample_cert_2.crt
  tests/unit/extra_certs/test_extra_certs.py
Labels: approved, jira/valid-reference, lgtm

#1245 OLS-598: Print bucket ownership controls
  scripts/data_collection/README.md
  scripts/data_collection/print_ownership_controls.py
Labels: approved, jira/valid-reference, lgtm

#1247 OLS-779: Bump-up Gradio to version 4.37.2
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1250 OLS-837: Bump-up setuptools to 70.3.0
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1252 Include runner.py into coverage report
  Makefile
Labels: approved, lgtm

#1258 OLS-833: Update package references for Cachi2 + fix vuln. in requirements.txt
  requirements-build.in
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1260 OLS-833: Sync llama-index packages with RAG repository
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1261 Don't read tenant id etc if dir contains apikey only
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1259 OLS-648: Fix DevConfig types
  ols/app/models/config.py
  ols/utils/auth_dependency.py
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1229 OLS-827: Add answers changed due to 4.16
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#1262 OLS-833: Bump-up all langchain packages ta latest CVE-free versions
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1267 Fixed return value type
  ols/app/models/config.py
Labels: approved, lgtm

#1269 Fixed validator return type
  ols/app/models/models.py
Labels: approved, lgtm

#1271 OLS-833: Bump-up Kubernetes and azure-identity packages
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1270 Repeat unstable e2e test
  tests/e2e/test_api.py
Labels: approved, lgtm

#1264 Don't override credentials when they are not specified in provider specific config
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/bam.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/watsonx.py
Labels: approved, lgtm

#1273 Removed dev-config completely - to be 'compatible' with customers settings
  tests/config/cluster_install/ols_configmap.yaml
Labels: approved, lgtm

#1265 OLS-833: Gradio is dev dependency
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1268 Fix linter warnings when provider-specific config is None
  ols/app/models/config.py
Labels: approved, lgtm

#1277 upgrade ecosystem-cert-preflight-checks due fixing EC issues
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1283 Specify buildah-6gb version
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1285 OLS-833: Bump-up Ruff to version 0.5.2
  pdm.lock
  pyproject.toml
  scripts/evaluation/driver.py
  tests/e2e/utils/client.py
  tests/e2e/utils/decorators.py
Labels: approved, jira/valid-reference, lgtm

#1287 OLS-804: update ibm-cos-sdk library explicitly
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1288 Evaluation - Update granite eval7 answer for 4.16
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, lgtm

#1289 OLS-804: Update urllib3 to version 2.2.2 to avoid CVE
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1291 OLS-804, OLS-833, OLS-837, OLS-838: Update package list for Cachi2
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1280 OLS-774: Better HTTPException error content
  ols/app/endpoints/feedback.py
  ols/app/endpoints/ols.py
  ols/utils/errors_parsing.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1292 Adding upload_artifact_s3
  pdm.lock
  pyproject.toml
  scripts/upload_artifact_s3.py
Labels: approved, lgtm

#1302 OLS-821: Update buildah-6b to latest 0.1
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1303 OLS-821: Update Konflux references without buildah-6b (keep old version)
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, jira/valid-reference, lgtm

#1305 Update buildah-6b to version 0.2
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1306 Bump-up `task-init`
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1307 Buildah-6g applicable for 2024-07-23
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1308 Bump-up task-source-build
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1310 Fix OLS-874: security issue in lanchchain-community
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1311 Fix OLS-824 for Cachi2 package list
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, lgtm

#1312 OLS-567: Added vendor label
  Containerfile
Labels: approved, jira/valid-reference, lgtm

#1317 Added link to JUnit test framework
  CONTRIBUTING.md
Labels: approved, lgtm

#1320 OLS-882: Setup tools fix
  Makefile
  constraints.txt
Labels: approved, jira/valid-reference, lgtm

#1321 Bump-up buildah-6g again
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1322 Bump-up task-git-clone to latest available
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1323 OLS-884: use the bug-free latest setuptools on CI
  Makefile
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1324 OLS-884: Bump-up to latest setuptools 72.1.0
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1295 Update SNYK configuration
  .snyk
Labels: approved, lgtm

#1330 OLS-884: Update dependencies for cachi2 after setuptools bump-up
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1331 Assign before return statement is not needed
  ols/src/cache/in_memory_cache.py
  ols/src/cache/postgres_cache.py
Labels: approved, lgtm

#1332 Removed redundant open modes
  ols/app/models/config.py
  ols/utils/config.py
Labels: approved, lgtm

#1335 Idiomatic iteration over dictionary keys
  ols/app/metrics/metrics.py
Labels: approved, lgtm

#1337 Bump-up faiss-cpu package to 1.8.0.post1
  pdm.lock
  pyproject.toml
Labels: approved, lgtm
