Repository openshift/lightspeed-service, pull requests merged in 2024-06, with the labels that each got.

#1013 Bump-up Black devel dependency to 24.4.0
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1014 Update to PR template - new change type
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#1004 rename & organize e2e utils
  tests/e2e/test_api.py
  tests/e2e/utils/__init__.py
  tests/e2e/utils/client.py
  tests/e2e/utils/cluster.py
  tests/e2e/utils/constants.py
  tests/e2e/utils/decorators.py
  tests/e2e/utils/metrics.py
  tests/e2e/utils/postgres.py
  tests/e2e/utils/response_evaluation.py
  tests/scripts/must_gather.py
Labels: approved, lgtm

#1008 Add more QnAs for resp eval
  tests/test_data/question_answer_pair.json
Labels: approved, lgtm

#1017 OLS-673: Bump-up devel tool Mypy to version 1.10.0
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1011 add questions pool for reference
  tests/test_data/question_answer_pair.json
Labels: approved, lgtm

#1016 OLS-641: Check if credentials path is loaded from provider config only
  tests/config/valid_config_with_azure_openai_2.yaml
  tests/config/valid_config_with_bam_2.yaml
  tests/config/valid_config_with_watsonx_2.yaml
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1012 OLS-505: Refactor script scripts/question_gen.py
  scripts/questions_gen.py
Labels: approved, jira/valid-reference, lgtm

#1021 Small fix for possible index array error
  scripts/questions_gen.py
Labels: approved, lgtm

#882 OLS-546: Use cluster id as user id
  ols/constants.py
  ols/user_data_collection/data_collector.py
  ols/utils/auth_dependency.py
  runner.py
  tests/config/cluster_install/ols_manifests.yaml
  tests/e2e/test_api.py
  tests/e2e/utils/cluster.py
  tests/mock_classes/mock_k8s_api.py
  tests/unit/utils/test_auth_dependency.py
Labels: approved, jira/valid-reference, lgtm

#1024 Added TODO for OLS-679
  ols/src/llms/providers/azure_openai.py
Labels: approved, lgtm

#1026 OLS-648: added type ignore to silent Mypy on CI
  ols/utils/auth_dependency.py
Labels: approved, jira/valid-reference, lgtm

#1027 OLS-648: Fix for currently unsupported Mypy multiple-line-statement behavior
  ols/utils/auth_dependency.py
Labels: approved, jira/valid-reference, lgtm

#1028 Fixed OLS-673-related issues
  ols/app/endpoints/ols.py
  ols/app/models/config.py
  ols/src/query_helpers/docs_summarizer.py
  ols/utils/token_handler.py
Labels: approved, lgtm

#1025 OLS-624: REST API schema for /query endpoint with optional list of attachments
  docs/openapi.json
  ols/app/models/models.py
Labels: approved, jira/valid-reference, lgtm

#1029 OLS-657: Bump-up ibm-generative-ai
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1023 Update ols-tls yaml in example for new CR perms
  examples/openshift-lightspeed-tls.yaml
Labels: approved, ok-to-test, lgtm

#1031 OLS-657: Bump-up langchain to 0.2.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1032 Bump-up `pytest` and `pytest-asyncio` devel packages
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1007 OLS-488: Readiness probe - index loading check
  docs/openapi.json
  ols/app/endpoints/health.py
  ols/app/models/models.py
  runner.py
  tests/e2e/test_api.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_openapi.py
  tests/unit/app/endpoints/test_health.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#1030 OLS-624: Disable additional properties + basic REST API tests with attachments
  docs/openapi.json
  ols/app/models/models.py
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#1036 Code simplification
  ols/app/metrics/metrics.py
Labels: approved, lgtm

#1035 OLS-663: Bug: When reference config is missing in config, use None instead of empty…
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1038 Pick up RAG content generated with the new asciidoc to plaintext converter
  Containerfile
  Makefile
Labels: approved, lgtm

#1037 (Trivial) Removed redundant exception in raise
  ols/src/cache/postgres_cache.py
  ols/utils/config.py
Labels: approved, lgtm

#1041 OLS-624: function to redact attachments
  ols/app/endpoints/ols.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1042 OLS-680: Moved secrets into separate directories
  tests/config/auth_config.yaml
  tests/config/config_without_logging.yaml
  tests/config/empty_openai_api_key.yaml
  tests/config/empty_secret/apitoken
  tests/config/secret/apitoken
  tests/config/secret2/apitoken
  tests/config/test_app_endpoints.yaml
  tests/config/valid_config.yaml
  tests/config/valid_config_postgres.yaml
  tests/config/valid_config_redis.yaml
  tests/config/valid_config_with_azure_openai.yaml
  tests/config/valid_config_with_azure_openai_2.yaml
  tests/config/valid_config_with_azure_openai_api_version.yaml
  tests/config/valid_config_with_azure_openai_tenant_and_client_id.yaml
  tests/config/valid_config_with_bam.yaml
  tests/config/valid_config_with_bam_2.yaml
  tests/config/valid_config_with_query_filter.yaml
  tests/config/valid_config_with_watsonx.yaml
  tests/config/valid_config_with_watsonx_2.yaml
  tests/config/valid_config_without_query_filter.yaml
  tests/config/with_openai_api_key.yaml
  tests/unit/app/models/test_config.py
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_openai.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1046 Add Xavier, remove Erik from approvers
  OWNERS
Labels: approved, lgtm

#1033 OLS-533: Add user data collection docs
  docs/user_data_flow.png
  docs/user_data_flow.uml
  ols/user_data_collection/README.md
Labels: approved, jira/valid-reference, lgtm

#1048 OLS-533: Fix diagram path in data collection docs
  ols/user_data_collection/README.md
Labels: approved, jira/valid-reference, lgtm

#1049 Use existing variable for wait indication in collector
  ols/user_data_collection/data_collector.py
Labels: approved, lgtm

#1050 Bump-up Gradio - security fix
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1047 Add resource limits to E2E testing
  tests/config/cluster_install/ols_manifests.yaml
Labels: approved, lgtm

#1051 OLS-692: OOM fix
  ols/user_data_collection/data_collector.py
Labels: approved, jira/valid-reference, lgtm

#1053 Bump-up devel dependency: pytest to 8.2.2.
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1034 OLS-624: Check attachments metadata
  ols/app/endpoints/ols.py
  ols/constants.py
  tests/e2e/test_api.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1054 Security fix: bump-up Gradio to 4.36.1
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1055 OLS-624: Do not shadow Python builtin functions
  ols/utils/redactor.py
Labels: approved, jira/valid-reference, lgtm

#1060 Updated the konflux build task with 6gb
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#1057 OLS-624: Attachments appender
  ols/app/endpoints/ols.py
  ols/src/query_helpers/attachment_appender.py
  tests/unit/query_helpers/test_attachment_appender.py
Labels: approved, jira/valid-reference, lgtm

#1062 Bump-up Pydantic to version 2.7.3
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1065 OLS-624: Added TODO for OLS-697
  ols/app/endpoints/ols.py
Labels: approved, jira/valid-reference, lgtm

#1063 Split unit test for invalid config
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#1064 Trivial refactoring: don't use magic constant for HTTP status code
  ols/user_data_collection/data_collector.py
Labels: approved, lgtm

#1056 Remove deprecated config options for providers for specific ols subpart
  tests/config/valid_config.yaml
  tests/config/valid_config_with_query_filter.yaml
  tests/config/valid_config_without_query_filter.yaml
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1066 OLS-624: more unit tests for attachment appender
  tests/unit/query_helpers/test_attachment_appender.py
Labels: approved, jira/valid-reference, lgtm

#1068 OLS-624: Integration tests for attachment appender
  tests/config/valid_config.yaml
  tests/integration/test_ols.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1061 Fix junit setup template variable name reference
  tests/scripts/utils.sh
Labels: approved, lgtm

#1069 OLS-624: Event is valid attachment type
  ols/constants.py
Labels: approved, jira/valid-reference, lgtm

#1070 Enable new Ruff rules on CI
  pyproject.toml
  tests/mock_classes/mock_llm_chain.py
Labels: approved, lgtm

#1071 OLS-708: Security fix: bump-up Azure identity to 1.16.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1073 Integration test for checking handling improper conversation ID
  tests/integration/test_feedback.py
Labels: approved, lgtm

#1074 OLS-712: TODO for OLS-712
  tests/e2e/utils/response_evaluation.py
Labels: approved, jira/valid-reference, lgtm

#1067 OLS-694: Improve memory usage in collector script by lazily loading llama_index
  ols/src/rag_index/index_loader.py
  ols/utils/config.py
  tests/config/cluster_install/ols_manifests.yaml
  tests/unit/rag_index/test_index_loader.py
Labels: approved, jira/valid-reference, lgtm

#1072 OLS-624: Tag for attachments tests
  tests/integration/pytest.ini
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1076 Full error message match test
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1079 Fix: added missing f-string
  ols/app/models/config.py
Labels: approved, lgtm

#1084 Fix project settings for Konflux
  pyproject.toml
Labels: approved, lgtm

#1080 OLS-624: Rest of integration tests for attachments
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1083 Remove check for deployment name existence
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1044 Adding fake llm provider
  ols/constants.py
  ols/src/llms/providers/fake_provider.py
  ols/src/llms/providers/provider.py
  tests/unit/llms/providers/test_fake_provider.py
  tests/unit/llms/providers/test_providers.py
Labels: approved, tide/merge-method-squash, lgtm

#1058 OLS-559: Handle smaller chunk size
  Containerfile
  Makefile
  ols/app/endpoints/ols.py
  ols/constants.py
  tests/e2e/test_api.py
  tests/e2e/utils/constants.py
  tests/test_data/question_answer_pair.json
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1075 Update example olsconfig.yaml to better suit for local OLS run
  examples/olsconfig.yaml
Labels: approved, lgtm

#1081 OLS-671: /readiness - LLM check
  ols/app/endpoints/health.py
  tests/integration/test_liveness_readiness.py
  tests/unit/app/endpoints/test_health.py
Labels: approved, jira/valid-reference, lgtm

#1086 fix readiness e2e test case
  tests/e2e/test_api.py
Labels: approved, lgtm

#1082 OLS-669: restructure QnA test data
  tests/e2e/conftest.py
  tests/e2e/utils/constants.py
  tests/e2e/utils/response_evaluation.py
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#1088 multiple eval answers to handle llm randomness
  tests/e2e/utils/response_evaluation.py
  tests/test_data/question_answer_pair.json
Labels: approved, lgtm

#1087 OLS-644: Use version-aligned OCP docs for RAG
  tests/config/cluster_install/ols_configmap.yaml
  tests/e2e/test_api.py
  tests/e2e/utils/cluster.py
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#1089 Improve isinstance check in llm_is_ready function
  ols/app/endpoints/health.py
Labels: approved, lgtm

#1090 OLS-721: Bump-up Uvicorn in order to create build requirements
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1091 OSL-721: Makefile target to generate requirements.txt file
  Makefile
Labels: approved, lgtm

#1092 Integration test to test if token counter checker is in place
  tests/integration/test_ols.py
Labels: approved, lgtm

#1093 OLS-739: Security fix: bump-up langchain and langchain-community
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1094 Integration test for missing config file
  tests/integration/test_config.py
Labels: approved, lgtm

#1095 OLS-624: test for testing too long/large attachment handling
  tests/integration/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1096 OLS-721: Target to check package list completeness
  Makefile
Labels: approved, jira/valid-reference, lgtm

#1098 OLS-721: specify build system
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#1099 Kubernetes-compatible YAML in docs
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/models/models.py
Labels: approved, lgtm

#1101 Bump-up Ruff to 0.4.9
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1104 Bump-up ML libraries
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1106 Removed leftovers (concatenated empty strings)
  tests/unit/app/endpoints/test_ols.py
  tests/unit/cache/test_postgres_cache.py
Labels: approved, lgtm

#1105 OLS-721: Requirements and requirements-build file needed by Cachi2/Konflux
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1109 Strings are concatenated implicitly, not need/want to use explicit concatenation
  scripts/data_collection/user_data_aggregator.py
  tests/unit/utils/test_redactor.py
Labels: approved, lgtm

#1107 Removed assignment to variable before return
  ols/app/endpoints/ols.py
  tests/e2e/utils/response_evaluation.py
  tests/integration/query_helpers/test_query_docs.py
  tests/unit/app/endpoints/test_feedback.py
Labels: approved, lgtm

#1111 Fixed unit test parametrization
  scripts/data_collection/user_data_aggregator.py
Labels: approved, lgtm

#1100 OLS-490: Sync Max response token for token handler with model parameter
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/constants.py
  ols/src/llms/providers/provider.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
  ols/utils/token_handler.py
  tests/config/valid_config.yaml
  tests/integration/test_ols.py
  tests/unit/app/models/test_config.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/utils/test_config.py
  tests/unit/utils/test_token_handler.py
Labels: approved, jira/valid-reference, lgtm

#1103 OLS-617: Add alert runbooks as a RAG content source
  Containerfile
  Makefile
Labels: approved, jira/valid-reference, lgtm

#1108 Idiomatic loop counter usage
  ols/utils/token_handler.py
Labels: approved, lgtm

#1112 Idiomatic re-raise without specifying the exception variable
  tests/e2e/utils/decorators.py
Labels: approved, lgtm

#1113 Use `OSError`, not `IOError`
  ols/app/models/config.py
Labels: approved, lgtm

#1114 OLS-490: Remove deprecated Extra and replace it with literals
  ols/app/models/config.py
Labels: approved, jira/valid-reference, lgtm

#1078 OLS-642: Redacted content should never be displayed in logs
  ols/app/endpoints/ols.py
  ols/utils/redactor.py
  tests/e2e/test_api.py
Labels: approved, jira/valid-reference, lgtm

#1116 OLS-721: Script to generate packages to prefetch in Cachi2
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#1118 OLS-721: Sync requirements.txt file with list of packages to prefetch
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1115 OLS-490: Refactor ModelConfig
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
  tests/unit/llms/providers/test_bam.py
  tests/unit/llms/providers/test_openai.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1117 OLS-581: Move the program logic to wait for OLS
  Makefile
  tests/e2e/conftest.py
  tests/e2e/test_api.py
  tests/e2e/utils/wait_for_ols.py
  tests/scripts/utils.sh
Labels: approved, jira/valid-reference, lgtm

#1122 Added missing unit tests for readiness endpoint
  tests/unit/app/endpoints/test_health.py
Labels: approved, lgtm

#1120 OLS-490: Add model_parameters config option
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/src/query_helpers/docs_summarizer.py
  tests/config/valid_config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#1125 OLS-721: ability to create list of build packages
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#1126 Bump-up Ruff to version 0.4.10
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1127 Autouse `_setup` fixture
  tests/integration/test_authorized.py
Labels: approved, lgtm

#1128 Don't have to pass setup fixture, it is autoused
  tests/integration/test_feedback.py
Labels: approved, lgtm

#1121 Simpler assertion in e2e test
  tests/e2e/test_api.py
Labels: approved, lgtm

#1133 Fixed rest of _setup fixtures usage
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_openapi.py
Labels: approved, lgtm

#1119 OLS-679: Azure token refresh
  ols/src/llms/providers/azure_openai.py
  tests/unit/llms/providers/test_azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#1135 OLS-702: Use non-root user in Containerfile
  Containerfile
Labels: approved, jira/valid-reference, lgtm

#1134 OLS-702: Copy license file into container
  Containerfile
Labels: approved, jira/valid-reference, lgtm

#1146 OLS-758: Fix CI job failures caused by newest Mypy version 1.10.1
  Makefile
Labels: approved, jira/valid-reference, lgtm

#1137 Usefixtures in integration tests who activelly does not use the fixture
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
Labels: approved, lgtm

#1144 Bump-up Bandit
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1145 Remove `jq` tool from service dependency
  Containerfile
Labels: approved, lgtm

#1148 Use fixtures in unit tests
  tests/unit/app/endpoints/test_authorized.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/utils/test_auth_dependency.py
Labels: approved, lgtm

#1132 Fix user warning in model config
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/src/query_helpers/docs_summarizer.py
  tests/config/valid_config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#1150 Minor fixes for issues found in our sources
  ols/user_data_collection/data_collector.py
  ols/utils/auth_dependency.py
  ols/utils/config.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, lgtm

#1130 Refactor logging config
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
  tests/unit/ui/test_gradio_ui.py
  tests/unit/utils/test_logging.py
Labels: approved, lgtm

#1155 OLS-756: attachments on Google sheet table
  scripts/data_collection/user_data_aggregator.py
Labels: approved, jira/valid-reference, lgtm

#1153 Bump-up types-requests used by pytest
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1154 Removed dead code from test
  tests/unit/cache/test_postgres_cache.py
Labels: approved, lgtm

#1149 Fix JSONDecodeError in collector
  ols/user_data_collection/data_collector.py
Labels: approved, lgtm

#1147 OLS-431: evaluation using groundtruth
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
  tests/e2e/utils/response_evaluation.py
  tests/scripts/test-e2e-cluster.sh
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#1160 fix: retain api url for local e2e run
  tests/e2e/test_api.py
Labels: approved, lgtm

#1156 Don't test for 'any' exception, we should be more specific
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#1157 Pandas is now direct dependency
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1161 Refactor: use existing function to run oc command from cluster utils
  tests/e2e/test_api.py
Labels: approved, lgtm

#1158 Disable collector script by default for other than collector tests
  tests/e2e/test_api.py
Labels: approved, lgtm

#1166 Bump-up Mypy to 1.10.1
  pdm.lock
  pyproject.toml
Labels: approved, lgtm

#1167 Ignore error when Mypy can not be uninstalled
  Makefile
Labels: approved, lgtm

#1162 Fixes: location is `tuple`, mapping is `dict`
  tests/e2e/conftest.py
Labels: approved, lgtm

#1168 Fixed wrong type hint
  scripts/data_collection/user_data_aggregator.py
Labels: approved, lgtm

#1169 Minor e2e tests improvements
  tests/e2e/test_api.py
Labels: approved, lgtm

#1170 Update ground-truth answer
  tests/test_data/question_answer_pair.json
Labels: approved, lgtm

#1164 OLS-431: add new query to question pool
  tests/test_data/question_answer_pair.json
Labels: approved, jira/valid-reference, lgtm

#1173 Minor fixes in config unit tests
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#1136 OLS-734: Add attachments to transcript
  ols/app/endpoints/ols.py
  tests/e2e/test_api.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#1175 OLS-775: import GradiIO just in devel mode
  ols/app/main.py
Labels: approved, jira/valid-reference, lgtm

#1172 Remove duplicated tests for health endpoints
  tests/e2e/test_api.py
Labels: approved, lgtm

#1174 Improve note about query redaction
  ols/app/endpoints/ols.py
Labels: approved, lgtm

#1178 Fix print whole Google sheet URL, not just the ID
  scripts/data_collection/update_google_sheet.py
Labels: approved, lgtm

#1180 e2e: Bit more precise attachment check
  tests/e2e/test_api.py
Labels: approved, lgtm

#1181 Use provider type, not provider name, as metrics label
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
Labels: approved, lgtm

#1179 Add some config default values and load those in data collector
  ols/app/models/config.py
  ols/user_data_collection/data_collector.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm
