Repository openshift/lightspeed-service, pull requests merged in 2025-04, with the labels that each got.

#2393 OLS-1627: Fix PG issue
  ols/src/cache/postgres_cache.py
  tests/unit/cache/test_postgres_cache.py
Labels: approved, jira/valid-reference, lgtm

#2375 Remove special formatting of the prompt
  ols/src/prompts/prompt_generator.py
  ols/src/prompts/prompts.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/tools/oc_cli.py
  ols/src/tools/tools.py
  ols/utils/token_handler.py
  scripts/evaluation/eval_data/question_answer_pair.json
  scripts/evaluation/utils/rag.py
  tests/benchmarks/test_token_handler.py
  tests/config/operator_install/olsconfig.crd.watsonx_introspection.yaml
  tests/e2e/test_query_endpoint.py
  tests/integration/test_ols.py
  tests/scripts/test-e2e-cluster.sh
  tests/unit/prompts/test_prompt_generator.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/tools/test_oc_cli.py
  tests/unit/utils/test_token_handler.py
Labels: approved, lgtm

#2397 EC violations fix, add 2 sast checks
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#2389 load-test: temp fix for fake-llm output format
  ols/src/query_helpers/docs_summarizer.py
Labels: approved, lgtm

#2399 change tool calling query
  tests/e2e/test_query_endpoint.py
Labels: approved, lgtm

#2400 OLS-1615: Customized prompts
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/models/models.py
  ols/constants.py
  ols/customize/__init__.py
  ols/customize/ols/prompts.py
  ols/src/prompts/prompt_generator.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  ols/src/ui/gradio_ui.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/endpoints/test_streaming_ols.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, jira/valid-reference, lgtm

#2401 OLS-1615: Note about @patch decorator deprecation
  tests/mock_classes/mock_llama_index.py
  tests/mock_classes/mock_redis_client.py
Labels: approved, jira/valid-reference, lgtm

#2383 Don't capture the literal error in case of wrong tool args
  ols/src/tools/tools.py
  tests/unit/tools/test_tools.py
Labels: approved, lgtm

#2402 OLS-1615: Reranker as customized part
  ols/customize/__init__.py
  ols/customize/ols/reranker.py
  ols/src/query_helpers/docs_summarizer.py
  tests/unit/query_helpers/test_docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#2403 Regenerated ToC
  README.md
Labels: approved, lgtm

#2410 OLS-1647: Fixed QuestionValidator benchmark
  tests/benchmarks/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#2404 OLS-1307: Update dependencies
  pdm.lock
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2417 OLS-1615: customizable service name
  docs/openapi.json
  ols/app/main.py
  ols/customize/__init__.py
  ols/customize/ols/metadata.py
  tests/e2e/test_api.py
  tests/integration/test_openapi.py
Labels: approved, jira/valid-reference, lgtm

#2419 Ability to debug e2e service startup issues
  tests/e2e/utils/cluster.py
  tests/e2e/utils/ols_installer.py
  tests/e2e/utils/retry.py
  tests/scripts/must_gather.py
Labels: approved, lgtm

#2411 eval: taxonomy - context & answer relevancy
  pdm.lock
  pyproject.toml
  requirements.txt
  scripts/evaluation/taxonomy_eval.py
  scripts/evaluation/utils/prompts.py
Labels: approved, lgtm

#2423 More unit tests for plugin loader
  tests/unit/plugins/test_plugins.py
Labels: approved, lgtm

#2422 add http_async_client for async invocations
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/provider.py
  ols/src/llms/providers/rhelai_vllm.py
  ols/src/llms/providers/rhoai_vllm.py
  tests/unit/llms/providers/test_openai.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/providers/test_rhelai_vllm.py
  tests/unit/llms/providers/test_rhoai_vllm.py
Labels: approved, lgtm

#2424 Fixed issue #1639 - ability to generate schema without full configuration file in place
  scripts/generate_openapi_schema.py
  scripts/olsconfig.yaml
Labels: approved, lgtm

#2425 LCORE-61: Proper Python version
  README.md
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2426 OLS-1612: Bump-up ibm-watson-ai to version 1.3.6
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2416 In the OCP docs version test, check the URL
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
Labels: approved, ok-to-test, lgtm

#2431 Fix make-schema target
  scripts/olsconfig.yaml
Labels: approved, lgtm

#2433 Updated docs: quota limits
  README.md
Labels: approved, lgtm

#2438 Changing the default make target to be the help
  Makefile
Labels: approved, lgtm

#2439 LCORE-22: Support for MCP configuration
  ols/app/models/config.py
  ols/constants.py
  ols/utils/config.py
  tests/config/config_for_integration_tests.yaml
  tests/config/valid_config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2441 Noop with token auth module
  ols/constants.py
  ols/src/auth/auth.py
  ols/src/auth/noop_with_token.py
  tests/unit/auth/test_auth.py
  tests/unit/auth/test_noop_with_token.py
Labels: approved, lgtm

#2442 LCORE-71: ability to provide MCP env variables
  ols/app/models/config.py
  ols/constants.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2391 OLS-1454: Enable introspection for both endpoints
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/metrics/token_counter.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/tools/oc_cli.py
  ols/src/tools/tools.py
  tests/e2e/test_streaming_query_endpoint.py
  tests/integration/test_ols.py
  tests/mock_classes/mock_llm_loader.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/endpoints/test_streaming_ols.py
  tests/unit/app/metrics/test_token_counter.py
  tests/unit/app/models/test_models.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/tools/test_oc_cli.py
  tests/unit/tools/test_tools.py
Labels: approved, jira/valid-reference, lgtm

#2452 Support Fake Streaming list LLM
  ols/app/models/config.py
  ols/src/llms/providers/fake_provider.py
  ols/src/llms/providers/provider.py
  tests/unit/llms/providers/test_fake_provider.py
Labels: approved, lgtm

#2308 OLS-1418: Config + IndexLoader update of multiple RAG support.
  examples/olsconfig.yaml
  ols/app/endpoints/health.py
  ols/app/endpoints/ols.py
  ols/app/models/config.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/rag_index/index_loader.py
  ols/utils/config.py
  tests/config/auth_config.yaml
  tests/config/config_for_integration_tests.yaml
  tests/config/config_for_integration_tests_8443.yaml
  tests/config/config_without_logging.yaml
  tests/config/invalid_config.yaml
  tests/config/minimal_config.yaml
  tests/config/test_app_endpoints.yaml
  tests/config/valid_config.yaml
  tests/config/valid_config_postgres.yaml
  tests/config/valid_config_redis.yaml
  tests/config/valid_config_with_query_filter.yaml
  tests/config/valid_config_without_certificate_directory.yaml
  tests/config/valid_config_without_query_filter.yaml
  tests/e2e/utils/ols_installer.py
  tests/unit/app/models/test_config.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/rag_index/test_index_loader.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2455 disable openai/watsonx introspection test suites temporarily
  tests/scripts/test-e2e-cluster.sh
Labels: approved, lgtm

#2453 OLS-1654: Connection.connect refactoring + connection decorator
  ols/src/cache/postgres_cache.py
  ols/src/quota/cluster_quota_limiter.py
  ols/src/quota/quota_limiter.py
  ols/src/quota/revokable_quota_limiter.py
  ols/src/quota/user_quota_limiter.py
  ols/utils/connection_decorator.py
  tests/unit/cache/test_postgres_cache.py
  tests/unit/utils/test_connection_decorator.py
Labels: approved, jira/valid-reference, lgtm

#2444 Refactor mcp server config
  ols/app/models/config.py
  tests/config/config_for_integration_tests.yaml
  tests/config/valid_config.yaml
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#2460 OLS-1643: Bump to version 0.3.4
  docs/openapi.json
  ols/version.py
  scripts/build-container.sh
Labels: approved, jira/valid-reference, lgtm

#2463 LCORE-83: bump-up PyTorch to 2.7.0
  pdm.lock
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2462 OLS-1654 recconnection for quota limiters
  ols/src/quota/quota_limiter.py
  ols/src/quota/revokable_quota_limiter.py
  ols/src/quota/token_usage_history.py
  tests/unit/quota/test_cluster_quota_limiter.py
  tests/unit/quota/test_token_usage_history.py
  tests/unit/quota/test_user_quota_limiter.py
Labels: approved, lgtm

#2464 OLS-1662 - Changing timeout for streaming tests
  tests/e2e/test_streaming_query_endpoint.py
  tests/e2e/utils/ols_installer.py
Labels: approved, lgtm

#2447 fix: introspection e2e flakiness
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
  tests/scripts/test-e2e-cluster.sh
Labels: approved, lgtm

#2470 Quota limit docs update
  README.md
Labels: approved, lgtm

#2465 fix: e2e number chunks retrieved check
  tests/e2e/test_query_endpoint.py
Labels: approved, lgtm

#2473 e2e: add streaming rag for introspection
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
Labels: approved, lgtm

#2475 Fixed OLS-1631: tests should not perform any API calls
  tests/unit/rag_index/test_index_loader.py
Labels: approved, jira/valid-reference, lgtm

#2446 eval: taxonomy eval-save to diff file based on method
  scripts/evaluation/taxonomy_eval.py
Labels: approved, lgtm

#2476 Ruff rule ignores in project file
  Makefile
  pyproject.toml
Labels: approved, lgtm

#2477 Added missing type annotations
  ols/app/models/models.py
  ols/src/prompts/prompt_generator.py
  ols/src/quota/quota_exceed_error.py
Labels: approved, lgtm
