Repository openshift/lightspeed-service, pull requests merged in 2025-07, with the labels that each got.

#2562 OLS-1857: set version to 1.0.1
  docs/openapi.json
  ols/version.py
  scripts/build-container.sh
Labels: jira/valid-reference, lgtm

#2536 OLS-1800: Add auth header for sse mcp config
  ols/app/models/config.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/tools/mcp_config_builder.py
  tests/integration/test_ols.py
  tests/unit/app/models/test_config.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/tools/test_mcp_config_builder.py
Labels: approved, jira/valid-reference, lgtm

#2564 Update dependencies
  ols/utils/ssl.py
  pdm.lock
  pyproject.toml
  requirements.txt
  scripts/generate_openapi_schema.py
  scripts/transform_coverage_report.py
  tests/integration/test_project_version_consistency.py
Labels: approved, lgtm

#2553 OLS-1772: Streamable http
  docs/config.puml
  ols/app/models/config.py
  ols/constants.py
  ols/src/tools/mcp_config_builder.py
  tests/unit/app/models/test_config.py
  tests/unit/tools/test_mcp_config_builder.py
Labels: approved, jira/valid-reference, lgtm

#2559 OLS-1797: Disallow specific args in tools
  ols/src/tools/tools.py
  tests/unit/tools/test_tools.py
Labels: approved, jira/valid-reference, lgtm

#2563 OLS-1407: Execute tools in parallel
  ols/src/tools/tools.py
  tests/unit/tools/test_tools.py
Labels: approved, jira/valid-reference, lgtm

#2569 async timeout increase
  ols/constants.py
Labels: approved, lgtm

#2560 e2e: additional config test - refactoring + byok
  Makefile
  tests/config/operator_install/olsconfig.crd.watsonx_byok1.yaml
  tests/config/operator_install/olsconfig.crd.watsonx_byok2.yaml
  tests/e2e/pytest.ini
  tests/e2e/test_query_endpoint.py
  tests/e2e/utils/ols_installer.py
  tests/scripts/test-e2e-cluster-periodics.sh
  tests/scripts/test-e2e-cluster.sh
  tests/scripts/test-evaluation.sh
  tests/scripts/utils.sh
Labels: approved, lgtm

#2572 OLS-1954: Bump to version 1.0.3
  docs/openapi.json
  ols/version.py
  scripts/build-container.sh
Labels: approved, jira/valid-reference, lgtm
