Repository openshift/lightspeed-service, pull requests merged in 2025-05, with the labels that each got.

#2479 Use Annotated in feedback endpoint handler
  ols/app/endpoints/feedback.py
Labels: approved, lgtm

#2482 Proper AppConfig parameter type to start quota runner
  ols/runners/quota_scheduler.py
Labels: approved, lgtm

#2478 Tools improvements
  ols/src/tools/oc_cli.py
  ols/src/tools/tools.py
  tests/integration/test_ols.py
  tests/mock_classes/mock_tools.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/tools/test_oc_cli.py
  tests/unit/tools/test_tools.py
Labels: approved, lgtm

#2486 Changed types for LLM providers chat objects
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/provider.py
  ols/src/llms/providers/rhelai_vllm.py
  ols/src/llms/providers/rhoai_vllm.py
  ols/src/llms/providers/watsonx.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/test_llm_loader.py
Labels: approved, lgtm

#2488 OLS-1687: Remove Redis as dependency
  ols/src/cache/cache_factory.py
  ols/src/cache/redis_cache.py
  pdm.lock
  pyproject.toml
  requirements.txt
  tests/integration/test_redis.py
  tests/unit/cache/test_cache_factory.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#2485 conf: konflux nudge ignore FBC
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#2489 Updated unit tests
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#2496 Use proper Response objects in tests
  tests/benchmarks/test_errors_parsing.py
  tests/unit/utils/test_errors_parsing.py
Labels: approved, lgtm

#2497 Minor fixes
  ols/plugins/__init__.py
  tests/integration/test_authorized.py
  tests/integration/test_metrics.py
  tests/mock_classes/mock_retrievers.py
  tests/unit/extra_certs/test_extra_certs.py
Labels: approved, lgtm

#2481 OLS-1715: openai provider allow custom CA
  ols/app/models/config.py
  ols/src/llms/providers/openai.py
  tests/unit/llms/providers/test_openai.py
Labels: approved, ok-to-test, jira/valid-reference, lgtm

#2498 Handling custom pytest attributes by linters
  tests/e2e/conftest.py
  tests/e2e/test_api.py
  tests/e2e/test_attachments.py
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
  tests/e2e/test_user_feedback.py
Labels: approved, lgtm

#2500 LCORE-133 remove support for Redis completely
  ols/app/models/config.py
  ols/constants.py
  tests/config/config_for_integration_tests.yaml
  tests/config/config_for_integration_tests_8443.yaml
  tests/config/config_for_integration_tests_quota_limiters.yaml
  tests/config/config_without_logging.yaml
  tests/config/redis_password.txt
  tests/config/valid_config_redis.yaml
  tests/integration/pytest.ini
  tests/mock_classes/mock_redis_client.py
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#2450 OLS-1176: add option to configure CA certificate of HTTPS proxy
  ols/app/models/config.py
  ols/src/llms/providers/provider.py
  ols/utils/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2501 LCORE-133: Removed Redis from documentation
  Makefile
  README.md
  docs/config.png
  docs/config.puml
Labels: approved, jira/valid-reference, lgtm

#2504 Removed Redis containter file
  Containerfile.redis
Labels: approved, lgtm

#2505 OLS-1714 sync with upstream + pg2 errors handler
  ols/app/endpoints/ols.py
  ols/app/metrics/metrics.py
  ols/src/quota/quota_limiter.py
Labels: approved, lgtm

#2507 OLS-1714: reconnect PostgreSQL quota DB when tables are deleted
  ols/src/quota/cluster_quota_limiter.py
  ols/src/quota/quota_limiter.py
  ols/src/quota/revokable_quota_limiter.py
  ols/src/quota/token_usage_history.py
  ols/src/quota/user_quota_limiter.py
Labels: approved, jira/valid-reference, lgtm

#2491 eval: update latest result 2025-05-07
  scripts/evaluation/eval_data/result/README.md
  scripts/evaluation/eval_data/result/model_evaluation_result-answer_relevancy.png
  scripts/evaluation/eval_data/result/model_evaluation_result-answer_similarity_llm.png
  scripts/evaluation/eval_data/result/model_evaluation_result-cos_score.png
  scripts/evaluation/eval_data/result/model_evaluation_result-rougeL_f1.png
  scripts/evaluation/eval_data/result/model_evaluation_result-rougeL_precision.png
  scripts/evaluation/eval_data/result/model_evaluation_result-rougeL_recall.png
  scripts/evaluation/eval_data/result/model_evaluation_summary.json
Labels: approved, lgtm

#2508 OLS-1714: Postgres storage unit tests hardening
  tests/unit/cache/test_postgres_cache.py
  tests/unit/quota/test_cluster_quota_limiter.py
  tests/unit/quota/test_token_usage_history.py
  tests/unit/quota/test_user_quota_limiter.py
Labels: approved, jira/valid-reference, lgtm

#2510 Fixed minor issues in evaluation tests script
  tests/e2e/evaluation/test_evaluation.py
Labels: approved, lgtm

#2511 OLS-1734: Bump to version 0.3.5
  docs/openapi.json
  ols/version.py
  scripts/build-container.sh
Labels: approved, jira/valid-reference, lgtm

#2513 Update oc_logs description with namespace
  mcp_local/openshift.py
Labels: approved, lgtm

#2515 Update user data flow diagram
  docs/user_data_flow.png
  docs/user_data_flow.uml
Labels: approved, lgtm

#2517 Minor fixes in OLS installer
  tests/e2e/utils/ols_installer.py
Labels: approved, lgtm

#2520 [minor] Silence Pyright's improper linting error
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_openapi.py
Labels: approved, lgtm

#2512 tool calling: fixes & improvements
  mcp_local/openshift.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
  tests/mcp_local/test_openshift.py
Labels: approved, ok-to-test, lgtm

#2521 Fixed mock retrieved node class
  tests/mock_classes/mock_retrieved_node.py
Labels: approved, lgtm

#2526 Fixed tools config tests
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_redactor.py
Labels: approved, lgtm

#2528 Minor fixes in evaluation scripts
  scripts/evaluation/rag_eval.py
  scripts/evaluation/response_evaluation.py
  scripts/evaluation/taxonomy_eval.py
  scripts/evaluation/utils/models.py
  scripts/evaluation/utils/relevancy_score.py
  scripts/evaluation/utils/response.py
  scripts/evaluation/utils/score.py
  scripts/evaluation/utils/similarity_score_llm.py
Labels: approved, lgtm

#2531 Proper model constructor for RagChunk
  tests/unit/app/endpoints/test_ols.py
Labels: approved, lgtm

#2502 OLS-1340: use default version of OCP docs RAG if the current version is not available
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2537 Bump mypy to 1.16.0
  pdm.lock
  requirements.txt
Labels: approved, lgtm

#2532 OLS-1774: Improve default error message
  ols/utils/errors_parsing.py
  tests/unit/app/endpoints/test_streaming_ols.py
Labels: approved, jira/valid-reference, lgtm
