Repository openshift/lightspeed-service, pull requests merged in 2025-01, with the labels that each got.

#2082 OLS-1321: Bump-up Mypy to 1.14.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2008 OLS-587 - Adding test_generated_service_certs_rotation
  tests/e2e/test_api.py
  tests/e2e/utils/cluster.py
  tests/scripts/test-e2e-cluster-periodics.sh
  tests/scripts/test-e2e-cluster.sh
Labels: approved, lgtm

#2081 OLS-1318: Bump-up Jinja2 to 3.1.5 to fix vulnerability
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2083 [backport] Allow systemprompt override for dev
  docs/openapi.json
  examples/olsconfig.yaml
  ols/app/endpoints/ols.py
  ols/app/models/config.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/ui/gradio_ui.py
  tests/integration/test_ols.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#2086 OLS-1318: Bump-up Jinja2 in requirements.txt
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2087 Allow pylint rule C0415 on CI
  ols/src/rag_index/index_loader.py
  ols/utils/pyroscope.py
  pyproject.toml
Labels: approved, lgtm

#2085 Specify encoding in all file open operation in tests
  tests/e2e/conftest.py
  tests/e2e/test_api.py
  tests/e2e/utils/cluster.py
  tests/integration/test_config.py
  tests/integration/test_openapi.py
  tests/integration/test_project_version_consistency.py
Labels: approved, lgtm

#2088 OLS-1311: Bump-up tqdm to 4.67.1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2084 eval: alternate ans for eval7 azure
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, lgtm

#2091 OLS-1323: Get rid of global variables in integration tests
  tests/integration/test_authorized.py
  tests/integration/test_feedback.py
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_ols.py
  tests/integration/test_openapi.py
  tests/integration/test_redis.py
Labels: approved, jira/valid-reference, lgtm

#2089 OLS-1311: Bump-up aiohttp to 3.11.10
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2093 OLS-1323: DevConfig `__eq__` special method
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2094 OLS-1311: Bump-up cryptography package to version 44.0.0
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2090 OLS-1323: Refactoring: f-strings are possible in exception constructors
  tests/e2e/utils/cluster.py
Labels: approved, jira/valid-reference, lgtm

#2102 OLS-1323: Added missing unit test: TLS configuration without TLS key path attribute
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2104 OLS-1323: Enable Pylint for tests
  Makefile
Labels: approved, jira/valid-reference, lgtm

#2099 Updated config class diagram
  docs/config.png
  docs/config.puml
Labels: approved, lgtm

#2101 OLS-1325: Sync requirements.txt file
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2105 OLS-1311: Bump-up urllib3 to 2.2.3
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2108 OLS-1311: Bump-up faiss-cpu to version 1.9.0.post1
  pdm.lock
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2106 OLS-1323: Unit tests: QueryFilter equality checks
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2114 OLS-1325: sync requirements file
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2115 OLS-1325: Fixed filtering mechanism
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#2116 OLS-1323: Updated info about linters
  CONTRIBUTING.md
Labels: approved, jira/valid-reference, lgtm

#2117 OLS-1276: doc about system prompt override mechanism
  README.md
Labels: approved, jira/valid-reference, lgtm

#2112 use granite3 reference instead of granite2
  README.md
  examples/olsconfig.yaml
  ols/constants.py
  scripts/evaluation/driver.py
  scripts/evaluation/eval_data/question_answer_pair.json
  scripts/evaluation/utils/constants.py
  scripts/questions_gen.py
  tests/benchmarks/test_prompt_generator.py
  tests/config/auth_config.yaml
  tests/config/config_for_integration_tests.yaml
  tests/config/config_for_integration_tests_8443.yaml
  tests/config/minimal_config.yaml
  tests/config/operator_install/olsconfig.crd.bam.yaml
  tests/config/operator_install/olsconfig.crd.watsonx.yaml
  tests/config/test_app_endpoints.yaml
  tests/e2e/conftest.py
  tests/e2e/test_api.py
  tests/e2e/test_query_endpoint.py
  tests/e2e/utils/metrics.py
  tests/integration/test_ols.py
  tests/scripts/test-e2e-cluster-periodics.sh
  tests/scripts/test-e2e-cluster.sh
  tests/unit/app/models/test_config.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, lgtm

#2120 Assert attributes in session.config
  tests/e2e/conftest.py
Labels: approved, lgtm

#2121 OLS-1325: Ability to filter packages by architecture
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#2122 OLS-1325: Bump-up all packages in requirements.txt
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2123 chore: remove unnecessary exact model name reference during test
  ols/constants.py
  tests/benchmarks/test_prompt_generator.py
  tests/integration/test_ols.py
  tests/unit/app/models/test_config.py
  tests/unit/prompts/test_prompt_generator.py
Labels: approved, lgtm

#2125 config: konflux pipeline nudges related_images.json
  .tekton/lightspeed-service-push.yaml
Labels: approved, lgtm

#2124 eval: modified ans (eval2) for granite3
  scripts/evaluation/eval_data/question_answer_pair.json
Labels: approved, lgtm

#2131 OLS-1228: readable token counter textual representation
  ols/app/metrics/token_counter.py
  tests/unit/app/metrics/test_token_counter.py
Labels: approved, jira/valid-reference, lgtm

#2133 OLS-1331: sync PDM lockfile
  pdm.lock
Labels: approved, jira/valid-reference, lgtm

#2136 Enable Pylinter rule W1203
  pyproject.toml
Labels: approved, lgtm

#2130 OLS-1335: Ability to print actual configuration
  README.md
  runner.py
Labels: approved, jira/valid-reference, lgtm

#2132 OLS-1337: Fixed import for generic token counter unit tests
  tests/unit/app/metrics/test_token_counter.py
Labels: approved, jira/valid-reference, lgtm

#2134 Pylint for runner.py
  Makefile
  runner.py
Labels: approved, lgtm

#2127 fix(KONFLUX-6218): align repository ids to cpe mapping
  rpms.lock.yaml
  ubi.repo
Labels: approved, lgtm

#2140 Enable pylinter rule `E0401`
  pyproject.toml
  scripts/data_collection/update_google_sheet.py
Labels: approved, lgtm

#2141 Info about Redoc page
  README.md
Labels: approved, lgtm

#2014 OLS-39: Add streaming_query endpoint
  README.md
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/models/models.py
  ols/app/routers.py
  ols/constants.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_streaming_query_endpoint.py
  tests/integration/test_ols.py
  tests/mock_classes/mock_llm_loader.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/endpoints/test_streaming_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/query_helpers/test_docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#2149 System prompt UI widget unit test
  tests/unit/ui/test_gradio_ui.py
Labels: approved, lgtm

#2147 [backport] Support for not default Uvicorn port number for dev
  examples/olsconfig.yaml
  ols/app/models/config.py
  ols/runners/uvicorn.py
  tests/unit/app/models/test_config.py
  tests/unit/runners/test_uvicorn_runner.py
Labels: approved, ok-to-test, lgtm

#2150 Fixed type hints in streaming endpoint-related changes
  ols/app/endpoints/ols.py
Labels: approved, lgtm

#2151 Fixed type hints in config module
  ols/app/models/config.py
Labels: approved, lgtm

#2152 OLS-1228: TokenCounter as separate dataclass
  ols/app/endpoints/ols.py
  ols/app/metrics/token_counter.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/question_validator.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/metrics/test_token_counter.py
Labels: approved, jira/valid-reference, lgtm

#2153 OLS-1228: Token counters in OLS responses
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/models/models.py
  tests/e2e/test_query_endpoint.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_streaming_ols.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#2157 Docs: query mechanisms
  README.md
Labels: approved, lgtm

#2159 Enable Pylint rule `W0622` on CI
  ols/src/cache/redis_cache.py
  pyproject.toml
  tests/e2e/utils/cluster.py
  tests/e2e/utils/ols_installer.py
  tests/mock_classes/mock_llm_chain.py
Labels: approved, lgtm

#2158 Bug fix: `OLSConfig` equality
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
Labels: approved, lgtm

#2162 Adding new tag for user_data_collection test to not run in konflux
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
Labels: approved, lgtm

#2156 Constant query endpoints
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
Labels: approved, lgtm

#2163 Enable Pylinter rule `C0103`
  ols/app/endpoints/health.py
  pyproject.toml
  runner.py
  scripts/data_collection/download_ols_archive.py
  scripts/print_ec_failures.py
Labels: approved, lgtm

#2161 OLS-1352: User ID as optional REST API parameter
  docs/openapi.json
  ols/app/endpoints/authorized.py
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
Labels: approved, jira/valid-reference, lgtm

#2169 Fixed UML diagrams command
  Makefile
Labels: approved, lgtm

#2170 Don't redeclare outer scope vars by local ones
  ols/app/endpoints/feedback.py
  ols/utils/tls.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#2173 Pass `streaming` parameter to LLM loader
  ols/app/endpoints/health.py
  ols/app/endpoints/ols.py
  ols/src/llms/llm_loader.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  tests/mock_classes/mock_llm_loader.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/query_helpers/test_query_helper.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, lgtm

#2172 New commands to verify sources and packages
  pyproject.toml
Labels: approved, lgtm

#2174 Uvicorn port number in config diagram
  docs/config.png
  docs/config.puml
Labels: approved, lgtm

#2175 Pass streaming parameter to LLM providers explicitly
  ols/app/endpoints/health.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/azure_openai.py
  ols/src/llms/providers/openai.py
  ols/src/llms/providers/provider.py
  ols/src/llms/providers/rhelai_vllm.py
  ols/src/llms/providers/rhoai_vllm.py
  tests/unit/llms/providers/test_providers.py
Labels: approved, lgtm

#2182 [upstream] Re-enable system prompt override
  ols/src/query_helpers/docs_summarizer.py
  tests/unit/query_helpers/test_docs_summarizer.py
Labels: approved, lgtm

#2184 [Upstream][Feature] Event stream format support
  examples/olsconfig.yaml
  ols/app/endpoints/streaming_ols.py
  ols/app/models/config.py
  tests/unit/app/endpoints/test_streaming_ols.py
Labels: approved, lgtm
