Repository openshift/lightspeed-service, pull requests merged in 2025-03, with the labels that each got.

#2273 Added missing eq comparator
  ols/app/models/config.py
Labels: approved, lgtm

#2272 eval: latest eval score
  scripts/evaluation/eval_data/result/README.md
  scripts/evaluation/eval_data/result/model_evaluation_result-answer_relevancy.png
  scripts/evaluation/eval_data/result/model_evaluation_result-answer_similarity_llm.png
  scripts/evaluation/eval_data/result/model_evaluation_result-cos_score.png
  scripts/evaluation/eval_data/result/model_evaluation_result-rougeL_f1.png
  scripts/evaluation/eval_data/result/model_evaluation_result-rougeL_precision.png
  scripts/evaluation/eval_data/result/model_evaluation_result-rougeL_recall.png
  scripts/evaluation/eval_data/result/model_evaluation_summary.json
Labels: approved, lgtm

#2275 Added missing tests: user data collection attributes
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#2274 OLS-1467: Storing all user data collection parameters in config
  ols/app/models/config.py
  ols/user_data_collection/data_collector.py
Labels: approved, jira/valid-reference, lgtm

#2154 Loosen deps
  Containerfile
  Makefile
  README.md
  pdm.lock
  pyproject.toml
  requirements-build.in
  requirements-build.txt
  requirements.txt
Labels: approved, lgtm

#2282 Simplifying test run
  CONTRIBUTING.md
  Makefile
Labels: approved, lgtm

#2283 Unit tests for routers
  tests/unit/app/test_routers.py
Labels: approved, lgtm

#2286 OLS-1460: Allow Python 3.13 to be used
  README.md
  pyproject.toml
Labels: approved, jira/valid-reference, lgtm

#2285 OLS-1307: Unlock and bump torch
  pdm.lock
  pyproject.toml
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2292 OLS-1390: Quota limiters implementation
  ols/src/quota/__init__.py
  ols/src/quota/cluster_quota_limiter.py
  ols/src/quota/quota_exceed_error.py
  ols/src/quota/quota_limiter.py
  ols/src/quota/revokable_quota_limiter.py
  ols/src/quota/user_quota_limiter.py
  tests/unit/quota/__init__.py
  tests/unit/quota/test_cluster_quota_limiter.py
  tests/unit/quota/test_quota_exceed_error.py
  tests/unit/quota/test_user_quota_limiter.py
Labels: approved, jira/valid-reference, lgtm

#2287 OLS-1472: Update tool calling instructions
  ols/src/prompts/prompts.py
Labels: approved, jira/valid-reference, lgtm

#2290 update query validator benchmark script
  tests/benchmarks/test_question_validator.py
Labels: approved, lgtm

#2297 OLS-1390: Quota limiter as config property
  ols/app/models/config.py
  ols/utils/config.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2291 OLS-1404 - Move setup to conftest to run before any session starts.
  tests/e2e/conftest.py
  tests/e2e/pytest.ini
  tests/e2e/test_api.py
  tests/e2e/test_query_endpoint.py
Labels: approved, lgtm

#2293 eval: add summary flow
  scripts/evaluation/README.md
  scripts/evaluation/response_eval_flow.png
Labels: approved, lgtm

#2294 OLS-1360 - Removing not konflux tag from user-data-collection test
  tests/e2e/test_api.py
Labels: approved, lgtm

#2305 Added missing logging info for Uvicorn runner
  ols/runners/uvicorn.py
Labels: approved, lgtm

#2304 OLS-1307: Bump deps
  pdm.lock
  pyproject.toml
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#2303 OLS-1307: Evaluation as separate depenedency group
  Makefile
  pdm.lock
  pyproject.toml
  requirements.txt
  scripts/evaluation/README.md
Labels: approved, jira/valid-reference, lgtm

#2307 Quota limiter config tests
  ols/app/models/config.py
  tests/unit/app/models/test_config.py
  tests/unit/utils/test_config.py
Labels: approved, lgtm

#2309 OLS-1489 - Adding option to install bundle via provided image
  tests/e2e/utils/ols_installer.py
Labels: approved, lgtm

#2311 OLS-1390: Check token usage + consume tokens functionality
  ols/app/endpoints/ols.py
  ols/src/quota/quota_limiter.py
  tests/unit/app/endpoints/test_ols.py
Labels: approved, jira/valid-reference, lgtm

#2313 OLS-1462 - fixed mismatch between API documentation and actual behaviour
  docs/openapi.json
  ols/app/endpoints/streaming_ols.py
  tests/unit/app/endpoints/test_streaming_ols.py
Labels: approved, lgtm

#2281 OLS-1459: Token in oc
  README.md
  ols/src/query_helpers/docs_summarizer.py
  ols/src/tools/oc_cli.py
  ols/src/tools/tools.py
  tests/integration/test_ols.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/tools/test_oc_cli.py
  tests/unit/tools/test_tools.py
Labels: approved, jira/valid-reference, lgtm

#2320 Fetch openshift-clients from RHEL subscription content
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
  Containerfile
  artifacts.lock.yaml
  build.args
  redhat.repo
  rpms.in.yaml
  rpms.lock.yaml
Labels: approved, lgtm

#2318 HTTPX client unit test
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/llms/providers/test_watsonx.py
Labels: approved, lgtm

#2314 [minor] Explicitly set HTTP code for streaming response
  ols/app/endpoints/streaming_ols.py
Labels: approved, lgtm

#2319 Make target to render configuration diagram
  Makefile
Labels: approved, lgtm

#2148 OLS-670: readiness probe checks cache state
  ols/app/endpoints/health.py
  ols/src/cache/cache.py
  ols/src/cache/in_memory_cache.py
  ols/src/cache/postgres_cache.py
  ols/src/cache/redis_cache.py
  tests/mock_classes/mock_redis_client.py
  tests/unit/app/endpoints/test_health.py
  tests/unit/cache/test_in_memory_cache.py
  tests/unit/cache/test_postgres_cache.py
  tests/unit/cache/test_redis_cache.py
Labels: approved, jira/valid-reference, lgtm

#2316 Update oc tools
  ols/src/tools/oc_cli.py
Labels: approved, lgtm

#2325 OLS-1390: Quota scheduler
  ols/runners/quota_scheduler.py
  runner.py
  tests/config/config_for_integration_tests_quota_limiters.yaml
  tests/integration/test_runners.py
  tests/unit/runners/test_quota_scheduler_runner.py
Labels: approved, jira/valid-reference, lgtm

#2301 Readd the artifact gathering to the tests
  tests/e2e/conftest.py
  tests/e2e/test_api.py
Labels: approved, lgtm

#2315 eval: add chunk eval
  scripts/evaluation/rag_eval.py
  scripts/evaluation/response_evaluation.py
  scripts/evaluation/utils/constants.py
  scripts/evaluation/utils/plot.py
  scripts/evaluation/utils/prompts.py
Labels: approved, lgtm

#2327 OLS-1486: quota limiters to quota handlers
  ols/app/models/config.py
  ols/runners/quota_scheduler.py
  ols/src/quota/quota_limiter_factory.py
  ols/utils/config.py
  tests/config/config_for_integration_tests_quota_limiters.yaml
  tests/unit/app/models/test_config.py
  tests/unit/quota/test_quota_limiter_factory.py
  tests/unit/runners/test_quota_scheduler_runner.py
  tests/unit/utils/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2312 OLS-1307: Unlock all deps
  pdm.lock
  pyproject.toml
  requirements.txt
  scripts/generate_packages_to_prefetch.py
Labels: approved, jira/valid-reference, lgtm

#2326 Change version to 4.18 in prompt
  docs/openapi.json
  ols/src/prompts/prompts.py
Labels: approved, lgtm

#2330 OLS-1486: Consume tokens for streaming endpoint
  ols/app/endpoints/streaming_ols.py
Labels: approved, jira/valid-reference, lgtm

#2331 OLS-1515: Stop building RAG in Prow
  Containerfile
  build.args
Labels: approved, jira/valid-reference, lgtm

#2306 OLS-1386: Fix the cache value for azure token expiration
  ols/src/llms/providers/azure_openai.py
  tests/unit/llms/providers/test_azure_openai.py
Labels: approved, jira/valid-reference, lgtm

#2345 OLS-1486: Token usage history
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/models/config.py
  ols/src/quota/token_usage_history.py
  ols/utils/config.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/quota/test_token_usage_history.py
Labels: approved, jira/valid-reference, lgtm

#2346 Do not measure coverage for type checks imports
  .coveragerc
Labels: approved, lgtm

#2328 OLS-1405: Increase default context window size
  ols/constants.py
  scripts/evaluation/utils/models.py
  tests/e2e/test_query_endpoint.py
  tests/e2e/test_streaming_query_endpoint.py
  tests/unit/app/models/test_config.py
Labels: approved, jira/valid-reference, lgtm

#2347 OLS-1405: Update config UML diagram: added token history storage etc.
  docs/config.png
  docs/config.puml
Labels: approved, jira/valid-reference, lgtm

#2348 OLS-1521: Switch to new granite-3-8b-instruct model from IBM
  tests/e2e/test_streaming_query_endpoint.py
Labels: approved, jira/valid-reference, lgtm

#2333 OLS-1402: Add tool info in transcripts
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/models/models.py
  ols/src/query_helpers/docs_summarizer.py
  tests/e2e/test_api.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
  tests/unit/query_helpers/test_docs_summarizer.py
Labels: approved, jira/valid-reference, lgtm

#2353 OLS-1519: Remove mock connect decorator from quota unit tests
  tests/unit/quota/test_cluster_quota_limiter.py
  tests/unit/quota/test_quota_limiter_factory.py
  tests/unit/quota/test_user_quota_limiter.py
Labels: approved, jira/valid-reference, lgtm

#2350 OLS-1524: Remove dependabot configuration
  .github/dependabot.yml
Labels: approved, jira/valid-reference, lgtm

#2354 Updated arch diagram
  docs/architecture_diagram.png
  docs/architecture_diagram.uml
Labels: approved, lgtm

#2352 OLS-1307: Bump dependecies
  pdm.lock
  requirements.txt
Labels: approved, jira/valid-reference, lgtm

#1958 OLS-1256: Add OLS ARM builds to Konflux
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
  Containerfile
  rpms.lock.yaml
  ubi.repo
Labels: approved, jira/valid-reference, lgtm

#2355 OLS-1518: token limits in REST API responses
  docs/openapi.json
  ols/app/endpoints/ols.py
  ols/app/endpoints/streaming_ols.py
  ols/app/models/models.py
  ols/src/quota/quota_limiter.py
  ols/src/quota/revokable_quota_limiter.py
  tests/integration/test_ols.py
  tests/unit/app/endpoints/test_streaming_ols.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#2356 OLS-1519: Remove mock connect decorator from cache unit tests
  tests/unit/cache/test_cache_factory.py
  tests/unit/cache/test_postgres_cache.py
Labels: approved, jira/valid-reference, lgtm

#2349 OLS-1524: Add renovate.json
  renovate.json
Labels: approved, jira/valid-reference, lgtm

#2360 OLS-1517: Unified referenced documents in query endpoints
  docs/openapi.json
  ols/app/endpoints/streaming_ols.py
  ols/app/models/models.py
  scripts/evaluation/query_rag.py
  tests/e2e/test_query_endpoint.py
  tests/mock_classes/mock_query_engine.py
  tests/unit/app/endpoints/test_ols.py
  tests/unit/app/models/test_models.py
Labels: approved, jira/valid-reference, lgtm

#2359 Remove unused QueryDocs helper
  ols/src/query_helpers/query_docs.py
  tests/integration/query_helpers/test_query_docs.py
  tests/unit/query_helpers/test_query_docs.py
Labels: approved, lgtm

#2361 OLS-1519: mocked timestamps created via context manager
  tests/unit/quota/test_cluster_quota_limiter.py
  tests/unit/quota/test_token_usage_history.py
  tests/unit/quota/test_user_quota_limiter.py
Labels: approved, jira/valid-reference, lgtm

#2362 OLS-1519: no patch decorators in integration tests
  tests/integration/test_authorized.py
  tests/integration/test_ols.py
  tests/integration/test_runners.py
Labels: approved, jira/valid-reference, lgtm

#2363 OLS-1519: no @patch decorators in benchmarks
  tests/benchmarks/test_docs_summarizer.py
  tests/benchmarks/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#2374 OLS-1519: no @patch decorator in unit and integration tests
  tests/integration/test_liveness_readiness.py
  tests/integration/test_metrics.py
  tests/integration/test_openapi.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/query_helpers/test_question_validator.py
  tests/unit/rag_index/test_index_loader.py
  tests/unit/runners/test_quota_scheduler_runner.py
  tests/unit/runners/test_uvicorn_runner.py
Labels: approved, jira/valid-reference, lgtm

#2369 OLS-1549: fix - no metrics are gathered from serving undefined routes
  ols/app/main.py
  tests/integration/test_metrics.py
Labels: approved, lgtm

#2378 Fixed import sorting
  ols/app/main.py
Labels: approved, lgtm

#2379 Modifying section on patching to discourage use of decorators
  CONTRIBUTING.md
Labels: approved, lgtm

#2380 OLS-1519: Removed all remained @patch decorators from unit tests
  tests/unit/llms/providers/test_azure_openai.py
  tests/unit/llms/providers/test_watsonx.py
  tests/unit/llms/test_llm_loader.py
  tests/unit/utils/test_config.py
  tests/unit/utils/test_environments.py
Labels: approved, jira/valid-reference, lgtm

#2368 Update renovate.json config
  renovate.json
Labels: approved, lgtm

#2377 eval: fix issue post pandas upgrade
  scripts/evaluation/response_evaluation.py
Labels: approved, lgtm

#2372 Bump to version 0.3.3
  docs/openapi.json
  ols/version.py
  scripts/build-container.sh
Labels: approved, lgtm

#2370 OLS-1304: Build rag image in a separate konflux application to avoid EC failures in other repos
  .tekton/lightspeed-service-pull-request.yaml
  .tekton/lightspeed-service-push.yaml
  Containerfile
  Makefile
Labels: approved, jira/valid-reference, lgtm

#2351 OLS-1408: Enable introspection e2e
  ols/src/query_helpers/docs_summarizer.py
  ols/src/tools/oc_cli.py
  ols/src/tools/tools.py
  tests/e2e/test_query_endpoint.py
  tests/e2e/utils/ols_installer.py
  tests/scripts/test-e2e-cluster.sh
  tests/unit/tools/test_oc_cli.py
  tests/unit/tools/test_tools.py
Labels: approved, jira/valid-reference, lgtm

#2381 Updated architecture diagram
  docs/architecture_diagram.png
  docs/architecture_diagram.uml
Labels: approved, lgtm

#2371 Bump deps
  pdm.lock
  requirements.txt
Labels: approved, lgtm

#2382 OLS-1558: Minimal llama-index version specification to make Dependabot happy
  pyproject.toml
Labels: approved, ok-to-test, jira/valid-reference, lgtm

#2373 OLS-1454: Remove streaming parameter from providers
  ols/app/endpoints/health.py
  ols/app/endpoints/ols.py
  ols/src/llms/llm_loader.py
  ols/src/llms/providers/provider.py
  ols/src/query_helpers/docs_summarizer.py
  ols/src/query_helpers/query_helper.py
  ols/src/query_helpers/question_validator.py
  tests/unit/llms/providers/test_providers.py
  tests/unit/query_helpers/test_docs_summarizer.py
  tests/unit/query_helpers/test_query_helper.py
  tests/unit/query_helpers/test_question_validator.py
Labels: approved, jira/valid-reference, lgtm

#2384 rename ubi9 repos to conform with EC rules
  rpms.lock.yaml
  ubi.repo
Labels: approved, lgtm

#2388 Added missing unit tests for OLS helper functions
  tests/unit/app/endpoints/test_ols.py
Labels: approved, lgtm
